"""
Build 08_Full_Pipeline_V08.ipynb from an embedded, fully self-contained template.
Run: python "src/Full pipeline/build_v08.py"

Design goals:
1. No dependency on existing notebooks, prior versions, or external code files.
2. Regenerate the exact V08 notebook structure/content with outputs stripped.
3. Keep the full pipeline text in this script so it is reviewable/shareable.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DEFAULT = HERE / "08_Full_Pipeline_V08.ipynb"

# Full V08 notebook snapshot (outputs stripped)
NOTEBOOK_TEMPLATE_JSON = r'''{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8954ee25",
   "metadata": {},
   "source": [
    "# Rope Flow — Full Pipeline V08\n",
    "\n",
    "**Course:** MECH 798M / EECE 798K — Data-Driven Modeling  \n",
    "**Base:** V07 (Topology Features + Cycle-Matrix PCA + Min-Cycle Filter)  \n",
    "**V08 additions:**\n",
    "- "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cf26268",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, glob, re\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.signal import savgol_filter, find_peaks\n",
    "from scipy.linalg import svd\n",
    "from scipy.stats import skew, kurtosis\n",
    "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
    "from sklearn.svm import OneClassSVM\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.model_selection import LeaveOneGroupOut\n",
    "from sklearn.metrics import classification_report, f1_score, confusion_matrix, ConfusionMatrixDisplay\n",
    "from collections import Counter\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "np.random.seed(42)\n",
    "\n",
    "# ── Paths ────────────────────────────────────────────────────\n",
    "DATA_PROCESSED = os.path.join('..', '..', 'data', 'processed')\n",
    "\n",
    "CONFIG = {\n",
    "    'FS': 50.0,\n",
    "    'CYCLE_PROMINENCE_DEGS': 100.0,\n",
    "    'CYCLE_MIN_PERIOD_S': 0.5,\n",
    "    'CYCLE_MAX_PERIOD_S': 3.0,\n",
    "    'TARGET_LEN': 64,\n",
    "    'N_FOURIER_HARMONICS': 5,\n",
    "    'PCA_COMPONENTS': 6,\n",
    "    'TEMPLATE_CORR_THRESHOLD': 0.60,\n",
    "    'OCSVM_NU': 0.1,\n",
    "    'OCSVM_GAMMA': 'scale',\n",
    "    'MIN_CYCLE_SAMPLES': 10,\n",
    "    'CONFIDENCE_THRESHOLD': 0.7,      # GBM confidence gate for transition rejection\n",
    "    'TEMPLATE_GATE_THRESHOLD': 0.2,   # min template corr to accept a cycle\n",
    "}\n",
    "\n",
    "MACRO_MAP = {\n",
    "    'underhand': 'foundational', 'overhand': 'foundational',\n",
    "    'dragon_roll': 'advanced',\n",
    "    'sneak_underhand': 'sneak', 'sneak_overhand': 'sneak',\n",
    "    'race_and_chase': 'advanced', 'cheetahs_tail': 'advanced',\n",
    "}\n",
    "\n",
    "KNOWN_PATTERNS = set(MACRO_MAP.keys())\n",
    "\n",
    "PAL = {\n",
    "    'overhand': '#7F77DD', 'underhand': '#5DCAA5', 'dragon_roll': '#E24B4A',\n",
    "    'sneak_overhand': '#D85A30', 'sneak_underhand': '#EF9F27',\n",
    "    'race_and_chase': '#3498db', 'cheetahs_tail': '#e74c3c',\n",
    "    'transition': '#CCCCCC', 'unknown': '#888888',\n",
    "}\n",
    "\n",
    "plt.rcParams.update({\n",
    "    'figure.dpi': 120, 'axes.spines.top': False, 'axes.spines.right': False,\n",
    "    'axes.grid': True, 'grid.alpha': 0.3, 'font.size': 11,\n",
    "})\n",
    "\n",
    "\n",
    "# ── Results directory (new folder per run) ───────────────────\n",
    "import datetime\n",
    "RUN_NAME = datetime.datetime.now().strftime('run_%Y%m%d_%H%M%S')\n",
    "RESULTS_DIR = os.path.join('..', '..', 'results', 'Full_pipeline', RUN_NAME)\n",
    "os.makedirs(RESULTS_DIR, exist_ok=True)\n",
    "print(f'Results will be saved to: {RESULTS_DIR}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dea33a26",
   "metadata": {},
   "source": [
    "---\n",
    "## 2. Core pipeline functions "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb779895",
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_session(path_d0, path_d1):\n",
    "    d0 = pd.read_csv(path_d0)\n",
    "    d1 = pd.read_csv(path_d1)\n",
    "    return d0, d1\n",
    "\n",
    "def extract_signals(df):\n",
    "    t = df['timestamp_ms'].values / 1000.0\n",
    "    A = df[['ax_w', 'ay_w', 'az_w']].values\n",
    "    omega = df[['gx', 'gy', 'gz']].values * (np.pi / 180.0)\n",
    "    Q = df[['qw', 'qx', 'qy', 'qz']].values\n",
    "    return t, Q, A, omega\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 2. Cycle detection\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def detect_cycles(t, omega, fs=50.0):\n",
    "    mag = np.linalg.norm(omega, axis=1)\n",
    "    mag_smooth = savgol_filter(mag, window_length=15, polyorder=3)\n",
    "    prom_rads = CONFIG['CYCLE_PROMINENCE_DEGS'] * np.pi / 180.0\n",
    "    min_dist = int(CONFIG['CYCLE_MIN_PERIOD_S'] * fs)\n",
    "    peaks, _ = find_peaks(mag_smooth, distance=min_dist, prominence=prom_rads)\n",
    "    if len(peaks) < 2:\n",
    "        return [], mag_smooth, peaks\n",
    "    bounds = ([0]\n",
    "              + [(peaks[i] + peaks[i+1]) // 2 for i in range(len(peaks) - 1)]\n",
    "              + [len(t) - 1])\n",
    "    cycles = [(bounds[i], bounds[i+1]) for i in range(len(bounds) - 1)]\n",
    "    valid = []\n",
    "    for s, e in cycles:\n",
    "        dur = t[e] - t[s]\n",
    "        if (dur >= CONFIG['CYCLE_MIN_PERIOD_S'] and\n",
    "            dur <= CONFIG['CYCLE_MAX_PERIOD_S'] and\n",
    "            (e - s) >= CONFIG['MIN_CYCLE_SAMPLES']):\n",
    "            valid.append((s, e))\n",
    "    return valid, mag_smooth, peaks\n",
    "\n",
    "def pair_cycles(t0, cyc0, t1, cyc1):\n",
    "    def overlap(s0, e0, s1, e1):\n",
    "        return max(0.0, min(t0[e0], t1[e1]) - max(t0[s0], t1[s1]))\n",
    "    paired0, paired1, used = [], [], set()\n",
    "    for c0 in cyc0:\n",
    "        best_idx, best_ov = -1, -1.0\n",
    "        for i, c1 in enumerate(cyc1):\n",
    "            if i in used:\n",
    "                continue\n",
    "            ov = overlap(c0[0], c0[1], c1[0], c1[1])\n",
    "            if ov > best_ov:\n",
    "                best_ov, best_idx = ov, i\n",
    "        if best_idx >= 0 and best_ov > 0:\n",
    "            paired0.append(c0)\n",
    "            paired1.append(cyc1[best_idx])\n",
    "            used.add(best_idx)\n",
    "    return paired0, paired1\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 3. Fourier decomposition\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def fourier_features(signal_segment, fs, n_harmonics=5):\n",
    "    N = len(signal_segment)\n",
    "    if N < 8:\n",
    "        return np.zeros(3 + n_harmonics)\n",
    "    sig = signal_segment - np.mean(signal_segment)\n",
    "    F = np.abs(np.fft.rfft(sig))\n",
    "    freqs = np.fft.rfftfreq(N, 1.0 / fs)\n",
    "    F[0] = 0\n",
    "    power = F ** 2\n",
    "    total_power = np.sum(power) + 1e-12\n",
    "    dom_idx = np.argmax(F[1:]) + 1\n",
    "    dom_freq = freqs[dom_idx]\n",
    "    spectral_centroid = np.sum(freqs * power) / total_power\n",
    "    f0 = dom_freq\n",
    "    harmonic_ratios = np.zeros(n_harmonics)\n",
    "    for h in range(n_harmonics):\n",
    "        target_freq = f0 * (h + 1)\n",
    "        if target_freq > freqs[-1]:\n",
    "            break\n",
    "        idx = np.argmin(np.abs(freqs - target_freq))\n",
    "        lo = max(1, idx - 1)\n",
    "        hi = min(len(F), idx + 2)\n",
    "        harmonic_ratios[h] = np.sum(power[lo:hi]) / total_power\n",
    "    p_norm = power[1:] / (np.sum(power[1:]) + 1e-12)\n",
    "    p_norm = p_norm[p_norm > 0]\n",
    "    spectral_entropy = -np.sum(p_norm * np.log2(p_norm + 1e-12))\n",
    "    return np.concatenate([[dom_freq, spectral_centroid, spectral_entropy],\n",
    "                           harmonic_ratios])\n",
    "\n",
    "def cycle_fourier_features(A, omega, s, e, fs):\n",
    "    nh = CONFIG['N_FOURIER_HARMONICS']\n",
    "    feats = []\n",
    "    omega_mag = np.linalg.norm(omega[s:e], axis=1)\n",
    "    feats.append(fourier_features(omega_mag, fs, nh))\n",
    "    acc_mag = np.linalg.norm(A[s:e], axis=1)\n",
    "    feats.append(fourier_features(acc_mag, fs, nh))\n",
    "    return np.concatenate(feats)\n",
    "\n",
    "FOURIER_DIM = 2 * (3 + CONFIG['N_FOURIER_HARMONICS'])\n",
    "FOURIER_NAMES = []\n",
    "for ch in ['omega_mag', 'acc_mag']:\n",
    "    FOURIER_NAMES += [f'{ch}_dom_freq', f'{ch}_spec_centroid', f'{ch}_spec_entropy']\n",
    "    FOURIER_NAMES += [f'{ch}_harm_{i}' for i in range(CONFIG['N_FOURIER_HARMONICS'])]\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 4. Physics-grounded features\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def physics_features(t0, t1, A0, A1, om0, om1, s0, e0, s1, e1, fs):\n",
    "    tc0, tc1 = t0[s0:e0], t1[s1:e1]\n",
    "    a0, a1 = A0[s0:e0], A1[s1:e1]\n",
    "    w0, w1 = om0[s0:e0], om1[s1:e1]\n",
    "    period = tc0[-1] - tc0[0]\n",
    "    m0 = np.linalg.norm(w0, axis=1)\n",
    "    m1 = np.linalg.norm(w1, axis=1)\n",
    "    peak_omega = max(np.max(m0), np.max(m1))\n",
    "    mean_omega_d0 = np.mean(m0)\n",
    "    mean_omega_d1 = np.mean(m1)\n",
    "    acc_rms_d0 = np.sqrt(np.mean(np.sum(a0**2, axis=1)))\n",
    "    acc_rms_d1 = np.sqrt(np.mean(np.sum(a1**2, axis=1)))\n",
    "    acc_asym = acc_rms_d0 / (acc_rms_d1 + 1e-8)\n",
    "    omega_ratio = np.std(m0) / (np.std(m1) + 1e-8)\n",
    "    n_min = min(len(m0), len(m1))\n",
    "    if n_min > 4:\n",
    "        c0 = m0[:n_min] - m0[:n_min].mean()\n",
    "        c1 = m1[:n_min] - m1[:n_min].mean()\n",
    "        corr = np.correlate(c0, c1, mode='full')\n",
    "        lag_samples = np.argmax(corr) - (n_min - 1)\n",
    "        phase_lag = lag_samples / fs * 1000\n",
    "    else:\n",
    "        phase_lag = 0.0\n",
    "    if len(a0) > 2:\n",
    "        jerk = np.diff(a0, axis=0) * fs\n",
    "        jerk_rms = np.sqrt(np.mean(np.sum(jerk**2, axis=1)))\n",
    "    else:\n",
    "        jerk_rms = 0.0\n",
    "    e_rot = np.mean(m0**2) + np.mean(m1**2)\n",
    "    e_lin = np.mean(np.sum(a0**2, axis=1)) + np.mean(np.sum(a1**2, axis=1))\n",
    "    ke_ratio = e_rot / (e_rot + e_lin + 1e-8)\n",
    "    if len(m0) > 10:\n",
    "        m0c = m0 - m0.mean()\n",
    "        ac = np.correlate(m0c, m0c, mode='full')\n",
    "        ac = ac[len(m0c)-1:]\n",
    "        ac /= (ac[0] + 1e-12)\n",
    "        min_lag = max(2, int(0.3 * fs))\n",
    "        peaks_ac, props = find_peaks(ac[min_lag:], height=0)\n",
    "        periodicity = props['peak_heights'][0] if len(peaks_ac) > 0 else 0.0\n",
    "    else:\n",
    "        periodicity = 0.0\n",
    "    return np.array([\n",
    "        period, peak_omega, mean_omega_d0, mean_omega_d1,\n",
    "        acc_rms_d0, acc_rms_d1, acc_asym, omega_ratio,\n",
    "        phase_lag, jerk_rms, ke_ratio, periodicity\n",
    "    ])\n",
    "\n",
    "PHYSICS_NAMES = [\n",
    "    'period_s', 'peak_omega', 'mean_omega_d0', 'mean_omega_d1',\n",
    "    'acc_rms_d0', 'acc_rms_d1', 'acc_asymmetry', 'omega_std_ratio',\n",
    "    'phase_lag_ms', 'jerk_rms', 'ke_ratio', 'periodicity_score'\n",
    "]\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 5. SVD features\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def resample_cycle(signal, target_len):\n",
    "    n = len(signal)\n",
    "    if n < 2:\n",
    "        return np.zeros(target_len) if signal.ndim == 1 else np.zeros((target_len, signal.shape[1]))\n",
    "    x_old = np.linspace(0, 1, n)\n",
    "    x_new = np.linspace(0, 1, target_len)\n",
    "    if signal.ndim == 1:\n",
    "        return np.interp(x_new, x_old, signal)\n",
    "    else:\n",
    "        return np.column_stack([np.interp(x_new, x_old, signal[:, j])\n",
    "                                for j in range(signal.shape[1])])\n",
    "\n",
    "def build_cycle_matrix(A0, A1, om0, om1, s0, e0, s1, e1, target_len=64):\n",
    "    state0 = np.column_stack([A0[s0:e0], om0[s0:e0]])\n",
    "    state1 = np.column_stack([A1[s1:e1], om1[s1:e1]])\n",
    "    r0 = resample_cycle(state0, target_len)\n",
    "    r1 = resample_cycle(state1, target_len)\n",
    "    return np.column_stack([r0, r1]).T  # (12, target_len)\n",
    "\n",
    "def compute_svd_features(cycle_matrix, n_components=6):\n",
    "    U, S, Vt = svd(cycle_matrix, full_matrices=False)\n",
    "    S_ratio = S[:n_components] / (S[0] + 1e-12)\n",
    "    eff_rank = np.sum(S > 0.01 * S[0])\n",
    "    total_energy = np.sum(S**2)\n",
    "    return np.concatenate([S_ratio, [eff_rank, total_energy]])\n",
    "\n",
    "SVD_DIM = CONFIG['PCA_COMPONENTS'] + 2\n",
    "SVD_NAMES = ([f'sv_ratio_{i}' for i in range(CONFIG['PCA_COMPONENTS'])]\n",
    "             + ['eff_rank', 'total_energy'])\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 6. Template correlation\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def phase_align(cycle_matrix, reference, ref_channel=3):\n",
    "    \"\"\"\n",
    "    Circularly shift cycle_matrix to maximize correlation with reference\n",
    "    on a chosen channel (default: ωx of D0, row 3).\n",
    "    This removes arbitrary phase offset from cycle segmentation.\n",
    "    \"\"\"\n",
    "    x = cycle_matrix[ref_channel]\n",
    "    y = reference[ref_channel]\n",
    "    x_c = x - np.mean(x)\n",
    "    y_c = y - np.mean(y)\n",
    "    corr = np.correlate(np.tile(x_c, 2), y_c, mode='valid')\n",
    "    shift = np.argmax(corr)\n",
    "    if shift >= len(x):\n",
    "        shift -= len(x)\n",
    "    aligned = np.roll(cycle_matrix, -shift, axis=1)\n",
    "    return aligned, shift\n",
    "\n",
    "\n",
    "def build_template(all_cycle_matrices):\n",
    "    \"\"\"\n",
    "    Build overhand template via iterative phase alignment.\n",
    "    1. Initial template = median-energy cycle\n",
    "    2. Phase-align all cycles to it\n",
    "    3. Average the IQR-filtered aligned cycles\n",
    "    \"\"\"\n",
    "    energies = np.array([np.sum(m**2) for m in all_cycle_matrices])\n",
    "    # Start from the cycle closest to median energy\n",
    "    median_idx = np.argmin(np.abs(energies - np.median(energies)))\n",
    "    template = all_cycle_matrices[median_idx].copy()\n",
    "\n",
    "    # Iterative refinement (2 passes)\n",
    "    for iteration in range(2):\n",
    "        aligned = []\n",
    "        for cm in all_cycle_matrices:\n",
    "            cm_a, _ = phase_align(cm, template)\n",
    "            aligned.append(cm_a)\n",
    "        # IQR filter on energy\n",
    "        q25, q75 = np.percentile(energies, [25, 75])\n",
    "        mask = (energies >= q25) & (energies <= q75)\n",
    "        selected = [a for a, keep in zip(aligned, mask) if keep]\n",
    "        if len(selected) < 3:\n",
    "            selected = aligned\n",
    "        template = np.mean(selected, axis=0)\n",
    "\n",
    "    return template\n",
    "\n",
    "\n",
    "def template_correlation(cycle_matrix, template):\n",
    "    \"\"\"\n",
    "    Phase-aligned normalized correlation between cycle and template.\n",
    "    Returns mean and min correlation across all 12 channels.\n",
    "    \"\"\"\n",
    "    aligned, _ = phase_align(cycle_matrix, template)\n",
    "    n_channels = aligned.shape[0]\n",
    "    corrs = np.zeros(n_channels)\n",
    "    for ch in range(n_channels):\n",
    "        x = aligned[ch] - np.mean(aligned[ch])\n",
    "        y = template[ch] - np.mean(template[ch])\n",
    "        denom = (np.linalg.norm(x) * np.linalg.norm(y) + 1e-12)\n",
    "        corrs[ch] = np.dot(x, y) / denom\n",
    "    return np.mean(corrs), np.min(corrs)\n",
    "\n",
    "TEMPLATE_NAMES = ['template_corr_mean', 'template_corr_min']\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 7. DMD eigenvalue features — dynamical fingerprint\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def dmd_features(cycle_matrix, dt):\n",
    "    \"\"\"\n",
    "    DMD eigenvalue features — subject-invariant dynamical fingerprint.\n",
    "    Captures the linear operator governing one cycle's dynamics.\n",
    "    Returns top-3 frequencies, top-3 growth rates, rank, mean/max stability.\n",
    "    \"\"\"\n",
    "    X1, X2 = cycle_matrix[:, :-1], cycle_matrix[:, 1:]\n",
    "    U, S, Vh = svd(X1, full_matrices=False)\n",
    "    cumvar = np.cumsum(S**2) / (np.sum(S**2) + 1e-12)\n",
    "    r = min(int(np.searchsorted(cumvar, 0.99)) + 1, len(S), X1.shape[1])\n",
    "    r = max(r, 1)\n",
    "    A_t = U[:,:r].T @ X2 @ Vh[:r,:].T @ np.diag(1.0 / (S[:r] + 1e-12))\n",
    "    lam_d, _ = np.linalg.eig(A_t)\n",
    "    lam_c = np.log(np.maximum(np.abs(lam_d), 1e-12)) / dt\n",
    "    freqs = np.abs(lam_c.imag) / (2 * np.pi)\n",
    "    growth = lam_c.real\n",
    "    order = np.argsort(freqs)[::-1]\n",
    "    freqs, growth = freqs[order], growth[order]\n",
    "    n_top = 3\n",
    "    f_top, g_top = np.zeros(n_top), np.zeros(n_top)\n",
    "    for i in range(min(n_top, len(freqs))):\n",
    "        f_top[i] = freqs[i]; g_top[i] = growth[i]\n",
    "    return np.concatenate([f_top, g_top, [r, np.mean(growth), np.max(np.abs(growth))]])\n",
    "\n",
    "DMD_FEAT_NAMES = ([f'dmd_freq_{i}' for i in range(3)]\n",
    "                  + [f'dmd_growth_{i}' for i in range(3)]\n",
    "                  + ['dmd_rank', 'dmd_mean_growth', 'dmd_max_abs_growth'])\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 8. Subject-invariant features — ratios that cancel person effects\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def subject_invariant_features(t0, t1, A0, A1, om0, om1, s0, e0, s1, e1, fs):\n",
    "    \"\"\"\n",
    "    Features designed to be invariant to subject-specific scaling.\n",
    "    Uses D1/D0 ratios, statistical shape (skewness, kurtosis),\n",
    "    and inter-hand correlation — all dimensionless.\n",
    "    \"\"\"\n",
    "    from scipy.stats import skew, kurtosis as kurt\n",
    "    a0, a1 = A0[s0:e0], A1[s1:e1]\n",
    "    w0, w1 = om0[s0:e0], om1[s1:e1]\n",
    "    m0 = np.linalg.norm(w0, axis=1)\n",
    "    m1 = np.linalg.norm(w1, axis=1)\n",
    "    am0 = np.linalg.norm(a0, axis=1)\n",
    "    am1 = np.linalg.norm(a1, axis=1)\n",
    "    n = min(len(m0), len(m1))\n",
    "    return np.array([\n",
    "        np.mean(m1) / (np.mean(m0) + 1e-8),       # ω ratio D1/D0\n",
    "        np.mean(am1) / (np.mean(am0) + 1e-8),      # acc ratio D1/D0\n",
    "        np.std(m1) / (np.std(m0) + 1e-8),           # ω variability ratio\n",
    "        np.max(m1) / (np.max(m0) + 1e-8),           # peak ω ratio\n",
    "        skew(m0), skew(m1),                          # temporal shape\n",
    "        kurt(m0), kurt(m1),\n",
    "        np.corrcoef(m0[:n], m1[:n])[0, 1] if n > 4 else 0.0,  # inter-hand coupling\n",
    "    ])\n",
    "\n",
    "SI_FEAT_NAMES = ['omega_ratio_d1d0', 'acc_ratio_d1d0', 'omega_std_ratio_si',\n",
    "                 'peak_omega_ratio', 'skew_omega_d0', 'skew_omega_d1',\n",
    "                 'kurt_omega_d0', 'kurt_omega_d1', 'phase_coupling']\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 9. Full feature extraction\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "ALL_FEAT_NAMES = (PHYSICS_NAMES + FOURIER_NAMES + SVD_NAMES + TEMPLATE_NAMES\n",
    "                  + DMD_FEAT_NAMES + SI_FEAT_NAMES)\n",
    "N_FEAT = len(ALL_FEAT_NAMES)\n",
    "\n",
    "def extract_all_features(t0, t1, A0, A1, om0, om1,\n",
    "                         paired0, paired1, template, fs):\n",
    "    features = []\n",
    "    dt = 1.0 / fs\n",
    "    for (s0, e0), (s1, e1) in zip(paired0, paired1):\n",
    "        phys = physics_features(t0, t1, A0, A1, om0, om1, s0, e0, s1, e1, fs)\n",
    "        fourier = cycle_fourier_features(A0, om0, s0, e0, fs)\n",
    "        cm = build_cycle_matrix(A0, A1, om0, om1, s0, e0, s1, e1,\n",
    "                                CONFIG['TARGET_LEN'])\n",
    "        svd_feat = compute_svd_features(cm, CONFIG['PCA_COMPONENTS'])\n",
    "        corr_mean, corr_min = template_correlation(cm, template)\n",
    "        tmpl_feat = np.array([corr_mean, corr_min])\n",
    "        dmd_feat = dmd_features(cm, dt)\n",
    "        si_feat = subject_invariant_features(t0, t1, A0, A1, om0, om1,\n",
    "                                             s0, e0, s1, e1, fs)\n",
    "        feat = np.concatenate([phys, fourier, svd_feat, tmpl_feat,\n",
    "                               dmd_feat, si_feat])\n",
    "        features.append(feat)\n",
    "    return np.array(features)\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# 10. Multi-session training & cross-validation\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def process_session(path_d0, path_d1):\n",
    "    \"\"\"Load and preprocess a single session. Returns signals + cycle info.\"\"\"\n",
    "    d0, d1 = load_session(path_d0, path_d1)\n",
    "    t0, Q0, A0, om0 = extract_signals(d0)\n",
    "    t1, Q1, A1, om1 = extract_signals(d1)\n",
    "    fs = CONFIG['FS']\n",
    "    cyc0, mag0_smooth, peaks0 = detect_cycles(t0, om0, fs)\n",
    "    cyc1, _, _ = detect_cycles(t1, om1, fs)\n",
    "    p0, p1 = pair_cycles(t0, cyc0, t1, cyc1)\n",
    "    cms = [build_cycle_matrix(A0, A1, om0, om1, s0, e0, s1, e1, CONFIG['TARGET_LEN'])\n",
    "           for (s0, e0), (s1, e1) in zip(p0, p1)]\n",
    "    return {\n",
    "        't0': t0, 't1': t1, 'A0': A0, 'A1': A1, 'om0': om0, 'om1': om1,\n",
    "        'paired0': p0, 'paired1': p1, 'cycle_matrices': cms,\n",
    "        'mag0_smooth': mag0_smooth, 'peaks0': peaks0,\n",
    "    }\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "63263bdc",
   "metadata": {},
   "source": [
    "---\n",
    "## 3. Functions\n",
    "Adds heterogeneous session discovery, windowed cycle filtering,\n",
    "stratified group split, recording-group-aware LOSO, and held-out test evaluation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b3b2d738",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════════════════════\n",
    "#  FUNCTIONS\n",
    "# Adds: heterogeneous session discovery, windowed processing,\n",
    "#       stratified group split, updated train/classify/LOSO/evaluate\n",
    "# ══════════════════════════════════════════════════════════════════════════\n",
    "import re as _re, json as _json\n",
    "from collections import defaultdict\n",
    "\n",
    "DATA_RAW        = os.path.join('..', '..', 'data', 'raw')\n",
    "NEW_LABELED_RAW = os.path.join(DATA_RAW, 'new-labeled-sessions')\n",
    "\n",
    "# ── Label mapping (mirrors 08_Build_labels_index) ──────────────────────\n",
    "_EXACT_MAP = {\n",
    "    'underhand':'underhand','overhand':'overhand','dragon_roll':'dragon_roll',\n",
    "    'sneak_underhand':'sneak_underhand','sneak_overhand':'sneak_overhand',\n",
    "    'race_and_chase':'race_and_chase','cheetahs_tail':'cheetahs_tail',\n",
    "    'idle':None,\n",
    "}\n",
    "_PREFIX_RULES = [\n",
    "    (_re.compile(r'^us', _re.I), 'sneak_underhand'),\n",
    "    (_re.compile(r'^os', _re.I), 'sneak_overhand'),\n",
    "    (_re.compile(r'^u',  _re.I), 'underhand'),\n",
    "    (_re.compile(r'^o',  _re.I), 'overhand'),\n",
    "    (_re.compile(r'^fb', _re.I), 'dragon_roll'),\n",
    "    (_re.compile(r'^bf', _re.I), 'dragon_roll'),\n",
    "    (_re.compile(r'^cw$',  _re.I), None),\n",
    "    (_re.compile(r'^ccw$', _re.I), None),\n",
    "    (_re.compile(r'^idle', _re.I), None),\n",
    "    (_re.compile(r'^vq',   _re.I), None),\n",
    "]\n",
    "def _map_label(raw):\n",
    "    raw = raw.strip()\n",
    "    if raw.lower() in _EXACT_MAP:\n",
    "        return _EXACT_MAP[raw.lower()]\n",
    "    for pat, c in _PREFIX_RULES:\n",
    "        if pat.match(raw):\n",
    "            return c\n",
    "    return None\n",
    "\n",
    "\n",
    "# ── Session discovery ──────────────────────────────────────────────────\n",
    "def discover_sessions(processed_dir):\n",
    "    \"\"\"\n",
    "    Homogeneous sessions from unified-data.\n",
    "    Returns list of 5-tuples (d0, d1, label, display_name, time_windows=None).\n",
    "    \"\"\"\n",
    "    csv_files = sorted(glob.glob(os.path.join(processed_dir, '*_device0_processed.csv')))\n",
    "    sessions = []\n",
    "    for d0_path in csv_files:\n",
    "        d1_path = d0_path.replace('_device0_', '_device1_')\n",
    "        if not os.path.exists(d1_path):\n",
    "            continue\n",
    "        stem = os.path.basename(d0_path).replace('_device0_processed.csv', '')\n",
    "        parts = stem.split('_')\n",
    "        if len(parts) < 3:\n",
    "            continue\n",
    "        remaining = parts[2:]\n",
    "        label = None\n",
    "        for n in range(len(remaining), 0, -1):\n",
    "            if '_'.join(remaining[:n]) in KNOWN_PATTERNS:\n",
    "                label = '_'.join(remaining[:n])\n",
    "                subject = '_'.join(remaining[n:]) or 'unknown'\n",
    "                break\n",
    "        if label is None:\n",
    "            continue\n",
    "        display_name = f'{label}_{subject}'\n",
    "        sessions.append((d0_path, d1_path, label, display_name, None))\n",
    "    return sessions\n",
    "\n",
    "\n",
    "def discover_heterogeneous_sessions(processed_dir, raw_dir=None):\n",
    "    \"\"\"\n",
    "    Per-label entries from new-labeled-sessions JSON files.\n",
    "    One 5-tuple per (recording, canonical_label) pair.\n",
    "    display_name = 'session_name/label'  (slash used as LOSO group key separator)\n",
    "    time_windows = [(start_s, end_s), ...] for that label\n",
    "    \"\"\"\n",
    "    if raw_dir is None:\n",
    "        raw_dir = NEW_LABELED_RAW\n",
    "    if not os.path.isdir(raw_dir):\n",
    "        return []\n",
    "    entries = []\n",
    "    for sname in sorted(os.listdir(raw_dir)):\n",
    "        sdir = os.path.join(raw_dir, sname)\n",
    "        if not os.path.isdir(sdir):\n",
    "            continue\n",
    "        lpath = None\n",
    "        for fn in ('labels_corrected.json', 'labels.json'):\n",
    "            p = os.path.join(sdir, fn)\n",
    "            if os.path.isfile(p):\n",
    "                lpath = p\n",
    "                break\n",
    "        if lpath is None:\n",
    "            continue\n",
    "        d0 = os.path.join(processed_dir, f'{sname}_device0_processed.csv')\n",
    "        d1 = os.path.join(processed_dir, f'{sname}_device1_processed.csv')\n",
    "        if not (os.path.isfile(d0) and os.path.isfile(d1)):\n",
    "            continue\n",
    "        with open(lpath, encoding='utf-8') as fh:\n",
    "            data = _json.load(fh)\n",
    "        windows_by_label = defaultdict(list)\n",
    "        for seg in data.get('segments', []):\n",
    "            canon = _map_label(seg.get('label', ''))\n",
    "            if canon is None:\n",
    "                continue\n",
    "            s = seg.get('start')\n",
    "            e = seg.get('end')\n",
    "            if s is None:\n",
    "                continue\n",
    "            if e is None:\n",
    "                e = s + 2.0\n",
    "            windows_by_label[canon].append((float(s), float(e)))\n",
    "        for label, windows in sorted(windows_by_label.items()):\n",
    "            entries.append((d0, d1, label, f'{sname}/{label}', windows))\n",
    "    return entries\n",
    "\n",
    "\n",
    "def discover_all_sessions(processed_dir):\n",
    "    \"\"\"Combine homogeneous + heterogeneous entries, excluding sparse classes.\"\"\"\n",
    "    EXCLUDE_CLASSES = {'cheetahs_tail', 'race_and_chase'}\n",
    "    all_entries = discover_sessions(processed_dir) + discover_heterogeneous_sessions(processed_dir)\n",
    "    filtered = [e for e in all_entries if e[2] not in EXCLUDE_CLASSES]\n",
    "    excluded = [e for e in all_entries if e[2] in EXCLUDE_CLASSES]\n",
    "    if excluded:\n",
    "        print(f'Excluded {len(excluded)} entries from classes: {EXCLUDE_CLASSES}')\n",
    "    return filtered\n",
    "\n",
    "\n",
    "def session_group(entry):\n",
    "    \"\"\"Recording-level group key — slash in display_name separates session/label.\"\"\"\n",
    "    dn = entry[3]\n",
    "    return dn.split('/')[0] if '/' in dn else dn\n",
    "\n",
    "\n",
    "def summarize_sessions(sessions):\n",
    "    by_class = defaultdict(list)\n",
    "    for e in sessions:\n",
    "        by_class[e[2]].append(e[3])\n",
    "    print(f'Discovered {len(sessions)} entries across {len(by_class)} classes:')\n",
    "    for label in sorted(by_class.keys()):\n",
    "        names = by_class[label]\n",
    "        print(f'  {label:<22s}: {len(names):>3d} entries')\n",
    "        for n in names:\n",
    "            print(f'    - {n}')\n",
    "    singletons = [l for l, s in by_class.items() if len(s) == 1]\n",
    "    if singletons:\n",
    "        print(f'\\nWarning: {len(singletons)} singleton classes: {singletons}')\n",
    "    return dict(by_class)\n",
    "\n",
    "\n",
    "# ── Stratified group train/test split ─────────────────────────────────\n",
    "def stratified_group_split(sessions, test_fraction=0.2, random_state=42, min_train_fraction=0.8):\n",
    "    \"\"\"\n",
    "    Split sessions into train/test, keeping recording groups atomic.\n",
    "    Stratifies by estimated cycle count (not entry count) to prevent\n",
    "    inverted splits when heterogeneous groups have many entries.\n",
    "    Singletons (classes with only 1 group) always stay in train.\n",
    "    Enforces at least min_train_fraction in train (default: 80%).\n",
    "    \"\"\"\n",
    "    import random as _rand\n",
    "    rng = _rand.Random(random_state)\n",
    "\n",
    "    groups = defaultdict(list)\n",
    "    for e in sessions:\n",
    "        groups[session_group(e)].append(e)\n",
    "\n",
    "    # Estimate cycle count per group (use entry count as proxy if no data loaded)\n",
    "    group_weight = {g: len(entries) for g, entries in groups.items()}\n",
    "\n",
    "    class_to_groups = defaultdict(list)\n",
    "    for gname, entries in groups.items():\n",
    "        for lbl in set(e[2] for e in entries):\n",
    "            class_to_groups[lbl].append(gname)\n",
    "\n",
    "    test_groups = set()\n",
    "    for lbl, gnames in sorted(class_to_groups.items()):\n",
    "        if len(gnames) < 2:\n",
    "            continue  # singleton class — keep in train\n",
    "        # Sort by weight (smallest groups go to test first to avoid overshooting)\n",
    "        gnames_sorted = sorted(gnames, key=lambda g: group_weight[g])\n",
    "        rng.shuffle(gnames_sorted)\n",
    "        # Compute target: test_fraction of total entries for this class\n",
    "        total_entries = sum(len(groups[g]) for g in gnames)\n",
    "        target_test = max(1, total_entries * test_fraction)\n",
    "        if target_test >= total_entries * 0.2:\n",
    "            target_test = 1  # never put more than 1 group in test per class\n",
    "        test_count = 0\n",
    "        for g in gnames_sorted:\n",
    "            if g in test_groups:\n",
    "                test_count += len(groups[g])\n",
    "                continue\n",
    "            if test_count < target_test:  # strict: stop as soon as target met\n",
    "                test_groups.add(g)\n",
    "                test_count += len(groups[g])\n",
    "\n",
    "    # Enforce minimum train fraction (at least 80% by default)\n",
    "    total_entries = len(sessions)\n",
    "    max_test_entries = int(np.floor((1.0 - min_train_fraction) * total_entries))\n",
    "    current_test_entries = sum(len(groups[g]) for g in test_groups)\n",
    "    if current_test_entries > max_test_entries:\n",
    "        # Move smallest test groups back to train until constraint is satisfied\n",
    "        for g in sorted(list(test_groups), key=lambda k: len(groups[k])):\n",
    "            if current_test_entries <= max_test_entries:\n",
    "                break\n",
    "            test_groups.remove(g)\n",
    "            current_test_entries -= len(groups[g])\n",
    "\n",
    "    train = [e for e in sessions if session_group(e) not in test_groups]\n",
    "    test  = [e for e in sessions if session_group(e) in test_groups]\n",
    "\n",
    "    return train, test\n",
    "\n",
    "\n",
    "# ── Windowed session processing ────────────────────────────────────────\n",
    "def process_session_windowed(path_d0, path_d1, windows):\n",
    "    \"\"\"\n",
    "    Like process_session but only keeps cycles whose midpoint falls inside\n",
    "    one of the provided (start_s, end_s) windows.\n",
    "    \"\"\"\n",
    "    d0, d1 = load_session(path_d0, path_d1)\n",
    "    t0, _Q0, A0, om0 = extract_signals(d0)\n",
    "    t1, _Q1, A1, om1 = extract_signals(d1)\n",
    "    fs = CONFIG['FS']\n",
    "    cyc0, mag0_smooth, peaks0 = detect_cycles(t0, om0, fs)\n",
    "    cyc1, _, _ = detect_cycles(t1, om1, fs)\n",
    "    p0, p1 = pair_cycles(t0, cyc0, t1, cyc1)\n",
    "\n",
    "    fp0, fp1 = [], []\n",
    "    for (s0, e0), (s1, e1) in zip(p0, p1):\n",
    "        t_mid = (t0[s0] + t0[e0]) / 2.0\n",
    "        if any(ws <= t_mid < we for ws, we in windows):\n",
    "            fp0.append((s0, e0))\n",
    "            fp1.append((s1, e1))\n",
    "\n",
    "    cms = [build_cycle_matrix(A0, A1, om0, om1, s0, e0, s1, e1, CONFIG['TARGET_LEN'])\n",
    "           for (s0, e0), (s1, e1) in zip(fp0, fp1)]\n",
    "    return {\n",
    "        't0': t0, 't1': t1, 'A0': A0, 'A1': A1, 'om0': om0, 'om1': om1,\n",
    "        'paired0': fp0, 'paired1': fp1, 'cycle_matrices': cms,\n",
    "        'mag0_smooth': mag0_smooth, 'peaks0': peaks0,\n",
    "    }\n",
    "\n",
    "\n",
    "def _load_entry(entry):\n",
    "    \"\"\"Dispatch to process_session or process_session_windowed.\"\"\"\n",
    "    d0, d1, label, dname, tw = entry\n",
    "    return process_session(d0, d1) if tw is None else process_session_windowed(d0, d1, tw)\n",
    "\n",
    "\n",
    "# ── model training ───────────────────────────────────────────────────────\n",
    "def train_model(session_list, verbose=True, gbm_params=None):\n",
    "    \"\"\"\n",
    "    Train multi-class GBM from 5-tuple entries (homogeneous + heterogeneous).\n",
    "    Global scaling only (no per-entry z-scoring).\n",
    "    \"\"\"\n",
    "    fs = CONFIG['FS']\n",
    "    all_cms, all_sessions, all_labels = [], [], []\n",
    "\n",
    "    for entry in session_list:\n",
    "        d0, d1, label, dname, tw = entry\n",
    "        sess = _load_entry(entry)\n",
    "        all_sessions.append(sess)\n",
    "        all_cms.extend(sess['cycle_matrices'])\n",
    "        all_labels.append(label)\n",
    "        if verbose:\n",
    "            print(f'  {label:<22s} [{dname}]: {len(sess[\"paired0\"])} cycles')\n",
    "\n",
    "    if not all_cms:\n",
    "        raise ValueError('No cycles found — check processed data paths.')\n",
    "\n",
    "    template = build_template(all_cms)\n",
    "\n",
    "    class_cms = defaultdict(list)\n",
    "    for sess, lbl in zip(all_sessions, all_labels):\n",
    "        class_cms[lbl].extend(sess['cycle_matrices'])\n",
    "    class_templates = {lbl: build_template(cms) for lbl, cms in class_cms.items()}\n",
    "\n",
    "    X_list, y_list, sid_list = [], [], []\n",
    "    for si, (sess, lbl) in enumerate(zip(all_sessions, all_labels)):\n",
    "        X = extract_all_features(\n",
    "            sess['t0'], sess['t1'], sess['A0'], sess['A1'],\n",
    "            sess['om0'], sess['om1'], sess['paired0'], sess['paired1'],\n",
    "            template, fs)\n",
    "        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "        X_list.append(X)\n",
    "        y_list.extend([lbl] * len(X))\n",
    "        sid_list.extend([si] * len(X))\n",
    "\n",
    "    X_all   = np.vstack(X_list)\n",
    "    y_all   = np.array(y_list)\n",
    "    sid_all = np.array(sid_list)\n",
    "\n",
    "    # Global StandardScaler (fitted on training data only, no per-entry z-scoring)\n",
    "    # Per-entry z-scoring was erasing absolute kinematic magnitudes that\n",
    "    # discriminate patterns (e.g., dragon_roll has higher total_energy than underhand)\n",
    "    scaler  = StandardScaler()\n",
    "    X_s     = scaler.fit_transform(X_all)\n",
    "    le      = LabelEncoder()\n",
    "    y_enc   = le.fit_transform(y_all)\n",
    "\n",
    "    gbm_params = {} if gbm_params is None else dict(gbm_params)\n",
    "    params = {\n",
    "        'n_estimators': 300,\n",
    "        'max_depth': 3,\n",
    "        'learning_rate': 0.05,\n",
    "        'random_state': 42,\n",
    "    }\n",
    "    params.update(gbm_params)\n",
    "    clf = GradientBoostingClassifier(**params)\n",
    "    clf.fit(X_s, y_enc)\n",
    "\n",
    "    if verbose:\n",
    "        print(f'\\nTrained on {X_all.shape[0]} cycles x {X_all.shape[1]} features')\n",
    "        print(f'Classes: {list(le.classes_)}')\n",
    "        print(f'GBM params: {params}')\n",
    "\n",
    "    return {\n",
    "        'clf': clf, 'scaler': scaler, 'label_encoder': le,\n",
    "        'template': template, 'class_templates': class_templates,\n",
    "        'feature_names': ALL_FEAT_NAMES,\n",
    "        'X_train': X_all, 'y_train': y_all, 'session_ids': sid_all,\n",
    "    }\n",
    "\n",
    "\n",
    "# ──  classifier (windowed) ──────────────────────────────────────────\n",
    "def classify_session(path_d0, path_d1, model, time_windows=None, verbose=True,\n",
    "                          conf_threshold=None, tmpl_threshold=None):\n",
    "    \"\"\"\n",
    "    Classify with confidence + template transition rejection.\n",
    "    time_windows: list of (start_s, end_s) to restrict cycles (heterogeneous).\n",
    "    \"\"\"\n",
    "    fs   = CONFIG['FS']\n",
    "    sess = (process_session(path_d0, path_d1) if time_windows is None\n",
    "            else process_session_windowed(path_d0, path_d1, time_windows))\n",
    "\n",
    "    if not sess['paired0']:\n",
    "        return {'labels': [], 'confidences': [], 'X': np.array([]),\n",
    "                'verdict': 'unknown', 'vote': {}, 'n_transition': 0, 'session': sess}\n",
    "\n",
    "    X = extract_all_features(\n",
    "        sess['t0'], sess['t1'], sess['A0'], sess['A1'],\n",
    "        sess['om0'], sess['om1'], sess['paired0'], sess['paired1'],\n",
    "        model['template'], fs)\n",
    "    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "\n",
    "    if X.ndim < 2 or len(X) == 0:\n",
    "        if verbose:\n",
    "            print(f'  0 valid cycles — skipping')\n",
    "        return {'labels': [], 'confidences': [], 'X': np.empty((0, len(model['feature_names']))),\n",
    "                'verdict': 'unknown', 'vote': {}, 'n_transition': 0, 'session': sess}\n",
    "\n",
    "    # Use the global StandardScaler fitted on training data (no per-session z-scoring)\n",
    "    X_s = model['scaler'].transform(X)\n",
    "\n",
    "    le           = model['label_encoder']\n",
    "    y_pred_enc   = model['clf'].predict(X_s)\n",
    "    y_pred_proba = model['clf'].predict_proba(X_s)\n",
    "    pred_labels  = le.inverse_transform(y_pred_enc)\n",
    "    confidences  = np.max(y_pred_proba, axis=1)\n",
    "\n",
    "    conf_thr = CONFIG['CONFIDENCE_THRESHOLD'] if conf_threshold is None else conf_threshold\n",
    "    tmpl_thr = CONFIG['TEMPLATE_GATE_THRESHOLD'] if tmpl_threshold is None else tmpl_threshold\n",
    "    conf_gate = confidences >= conf_thr\n",
    "    tmpl_gate = np.zeros(len(X), dtype=bool)\n",
    "    for ci in range(len(X)):\n",
    "        cm = build_cycle_matrix(\n",
    "            sess['A0'], sess['A1'], sess['om0'], sess['om1'],\n",
    "            sess['paired0'][ci][0], sess['paired0'][ci][1],\n",
    "            sess['paired1'][ci][0], sess['paired1'][ci][1],\n",
    "            CONFIG['TARGET_LEN'])\n",
    "        for cls_tmpl in model['class_templates'].values():\n",
    "            if template_correlation(cm, cls_tmpl)[0] >= tmpl_thr:\n",
    "                tmpl_gate[ci] = True\n",
    "                break\n",
    "\n",
    "    labels = []\n",
    "    for i in range(len(X)):\n",
    "        labels.append(pred_labels[i] if (conf_gate[i] and tmpl_gate[i]) else 'transition')\n",
    "\n",
    "    non_trans = [l for l in labels if l != 'transition']\n",
    "    if non_trans:\n",
    "        vote    = Counter(non_trans)\n",
    "        verdict = vote.most_common(1)[0][0]\n",
    "    else:\n",
    "        vote    = Counter(labels)\n",
    "        verdict = 'unknown'\n",
    "\n",
    "    if verbose:\n",
    "        print(f'  {len(labels)} cycles | ', end='')\n",
    "        for cls, cnt in sorted(Counter(labels).items()):\n",
    "            print(f'{cls}={cnt} ', end='')\n",
    "        print(f'-> {verdict}')\n",
    "\n",
    "    return {\n",
    "        'labels': labels, 'confidences': confidences.tolist(), 'X': X,\n",
    "        'verdict': verdict, 'vote': dict(Counter(non_trans)),\n",
    "        'n_transition': sum(1 for l in labels if l == 'transition'),\n",
    "        'session': sess,\n",
    "    }\n",
    "\n",
    "\n",
    "# ── LOSO CV (recording-group aware) ──────────────────────────────────\n",
    "def run_loso(sessions, verbose=True, conf_threshold=None, tmpl_threshold=None, gbm_params=None):\n",
    "    \"\"\"\n",
    "    Leave-one-recording-group-out CV.\n",
    "    Group key = session_group(entry) so all segments from the same\n",
    "    physical recording stay on the same side of each fold.\n",
    "    Singleton groups are always in train.\n",
    "    \"\"\"\n",
    "    group_counts = Counter(session_group(e) for e in sessions)\n",
    "    class_group_counts = Counter(e[2] for e in sessions\n",
    "                                 if group_counts[session_group(e)] >= 1)\n",
    "\n",
    "    # Identify which classes appear in only one group → singleton\n",
    "    class_to_groups = defaultdict(set)\n",
    "    for e in sessions:\n",
    "        class_to_groups[e[2]].add(session_group(e))\n",
    "    singleton_classes = {c for c, gs in class_to_groups.items() if len(gs) == 1}\n",
    "\n",
    "    loso_groups = sorted(set(session_group(e) for e in sessions\n",
    "                             if e[2] not in singleton_classes))\n",
    "\n",
    "    if verbose and singleton_classes:\n",
    "        print(f'Singleton classes (train-only): {sorted(singleton_classes)}')\n",
    "        print(f'LOSO folds: {len(loso_groups)} recording groups')\n",
    "        print('=' * 80)\n",
    "\n",
    "    all_y_true, all_y_pred = [], []\n",
    "    entry_results = []\n",
    "\n",
    "    for test_grp in loso_groups:\n",
    "        test_entries  = [e for e in sessions if session_group(e) == test_grp]\n",
    "        train_entries = [e for e in sessions if session_group(e) != test_grp]\n",
    "\n",
    "        model = train_model(train_entries, verbose=False, gbm_params=gbm_params)\n",
    "\n",
    "        for entry in test_entries:\n",
    "            d0, d1, true_label, dname, tw = entry\n",
    "            res = classify_session(\n",
    "                d0, d1, model, time_windows=tw, verbose=False,\n",
    "                conf_threshold=conf_threshold, tmpl_threshold=tmpl_threshold)\n",
    "            if not res['labels']:\n",
    "                continue\n",
    "            non_trans = [l for l in res['labels'] if l != 'transition']\n",
    "            all_y_true.extend([true_label] * len(non_trans))\n",
    "            all_y_pred.extend(non_trans)\n",
    "            correct = res['verdict'] == true_label\n",
    "            entry_results.append((dname, true_label, res['verdict'], correct))\n",
    "            if verbose:\n",
    "                status = 'CORRECT' if correct else 'WRONG'\n",
    "                print(f'  {dname:<52s} GT={true_label:<20s} -> {res[\"verdict\"]:<20s} [{status}]')\n",
    "\n",
    "    n_correct = sum(1 for r in entry_results if r[3])\n",
    "    n_total   = len(entry_results)\n",
    "    print(f'\\nLOSO entry accuracy: {n_correct}/{n_total} '\n",
    "          f'({n_correct/n_total*100:.1f}%)' if n_total else '\\nNo LOSO results.')\n",
    "\n",
    "    result = {\n",
    "        'entry_results': entry_results,\n",
    "        'n_correct': n_correct, 'n_total': n_total,\n",
    "        'session_acc': n_correct / n_total if n_total else 0,\n",
    "    }\n",
    "    if all_y_true:\n",
    "        le = LabelEncoder()\n",
    "        le.fit(sorted(set(all_y_true + all_y_pred)))\n",
    "        yt, yp = le.transform(all_y_true), le.transform(all_y_pred)\n",
    "        print(classification_report(yt, yp, target_names=le.classes_, zero_division=0))\n",
    "        f1 = f1_score(yt, yp, average='macro', zero_division=0)\n",
    "        result.update({\n",
    "            'fine_report': classification_report(yt, yp, target_names=le.classes_, zero_division=0),\n",
    "            'fine_f1_macro': f1,\n",
    "            'fine_cm': confusion_matrix(yt, yp),\n",
    "            'fine_classes': le.classes_,\n",
    "            'all_y_true': all_y_true,\n",
    "            'all_y_pred': all_y_pred,\n",
    "        })\n",
    "        # Macro-class\n",
    "        mt = [MACRO_MAP.get(l, 'unknown') for l in all_y_true]\n",
    "        mp = [MACRO_MAP.get(l, 'unknown') for l in all_y_pred]\n",
    "        le_m = LabelEncoder()\n",
    "        le_m.fit(sorted(set(mt + mp)))\n",
    "        result.update({\n",
    "            'macro_report': classification_report(le_m.transform(mt), le_m.transform(mp),\n",
    "                                                  target_names=le_m.classes_, zero_division=0),\n",
    "            'macro_f1_macro': f1_score(le_m.transform(mt), le_m.transform(mp),\n",
    "                                       average='macro', zero_division=0),\n",
    "            'macro_cm': confusion_matrix(le_m.transform(mt), le_m.transform(mp)),\n",
    "            'macro_classes': le_m.classes_,\n",
    "        })\n",
    "    return result\n",
    "\n",
    "\n",
    "# ── Held-out test evaluation ───────────────────────────────────────────\n",
    "def evaluate_test_set(test_sessions, model, verbose=True, conf_threshold=None, tmpl_threshold=None):\n",
    "    \"\"\"\n",
    "    Evaluate the final model on held-out test entries.\n",
    "    Returns per-cycle and per-entry classification metrics.\n",
    "    \"\"\"\n",
    "    all_y_true, all_y_pred = [], []\n",
    "    entry_results = []\n",
    "\n",
    "    for entry in test_sessions:\n",
    "        d0, d1, true_label, dname, tw = entry\n",
    "        res = classify_session(\n",
    "            d0, d1, model, time_windows=tw, verbose=False,\n",
    "            conf_threshold=conf_threshold, tmpl_threshold=tmpl_threshold)\n",
    "        if not res['labels']:\n",
    "            continue\n",
    "        non_trans = [l for l in res['labels'] if l != 'transition']\n",
    "        all_y_true.extend([true_label] * len(non_trans))\n",
    "        all_y_pred.extend(non_trans)\n",
    "        correct = res['verdict'] == true_label\n",
    "        entry_results.append((dname, true_label, res['verdict'], correct))\n",
    "        if verbose:\n",
    "            status = 'CORRECT' if correct else 'WRONG'\n",
    "            print(f'  {dname:<52s} GT={true_label:<20s} -> {res[\"verdict\"]:<20s} [{status}]')\n",
    "\n",
    "    n_correct = sum(1 for r in entry_results if r[3])\n",
    "    n_total   = len(entry_results)\n",
    "    print(f'\\nTest entry accuracy: {n_correct}/{n_total} '\n",
    "          f'({n_correct/n_total*100:.1f}%)' if n_total else '\\nNo test entries.')\n",
    "\n",
    "    result = {\n",
    "        'entry_results': entry_results,\n",
    "        'n_correct': n_correct, 'n_total': n_total,\n",
    "    }\n",
    "    if all_y_true:\n",
    "        le = LabelEncoder()\n",
    "        le.fit(sorted(set(all_y_true + all_y_pred)))\n",
    "        yt, yp = le.transform(all_y_true), le.transform(all_y_pred)\n",
    "        print(classification_report(yt, yp, target_names=le.classes_, zero_division=0))\n",
    "        f1 = f1_score(yt, yp, average='macro', zero_division=0)\n",
    "        result.update({\n",
    "            'fine_report': classification_report(yt, yp, target_names=le.classes_, zero_division=0),\n",
    "            'test_f1_macro': f1,\n",
    "            'fine_cm': confusion_matrix(yt, yp),\n",
    "            'fine_classes': le.classes_,\n",
    "            'all_y_true': all_y_true,\n",
    "            'all_y_pred': all_y_pred,\n",
    "        })\n",
    "    return result\n",
    "\n",
    "\n",
    "# ── tuning helpers ───────────────────────────────────────────────\n",
    "def tune_thresholds(sessions, conf_grid, tmpl_grid, gbm_params=None, verbose=True):\n",
    "    \"\"\"\n",
    "    Grid-search confidence + template thresholds using LOSO F1 (macro).\n",
    "    Returns best thresholds and score.\n",
    "    \"\"\"\n",
    "    best = {'conf_threshold': None, 'tmpl_threshold': None, 'f1': -1.0}\n",
    "    for conf in conf_grid:\n",
    "        for tmpl in tmpl_grid:\n",
    "            res = run_loso(\n",
    "                sessions, verbose=False,\n",
    "                conf_threshold=conf, tmpl_threshold=tmpl,\n",
    "                gbm_params=gbm_params)\n",
    "            f1 = res.get('fine_f1_macro', 0.0)\n",
    "            if verbose:\n",
    "                print(f'  conf={conf:.2f} tmpl={tmpl:.2f} -> F1={f1:.3f}')\n",
    "            if f1 > best['f1']:\n",
    "                best = {'conf_threshold': conf, 'tmpl_threshold': tmpl, 'f1': f1}\n",
    "    if verbose and best['conf_threshold'] is not None:\n",
    "        print(f'Best thresholds: conf={best[\"conf_threshold\"]:.2f}, '\n",
    "              f'tmpl={best[\"tmpl_threshold\"]:.2f} (F1={best[\"f1\"]:.3f})')\n",
    "    return best\n",
    "\n",
    "\n",
    "def tune_gbm_params(sessions, gbm_grid, conf_threshold=None, tmpl_threshold=None, verbose=True):\n",
    "    \"\"\"\n",
    "    Small grid-search for GBM params using LOSO F1 (macro).\n",
    "    Returns best parameter set and score.\n",
    "    \"\"\"\n",
    "    best = {'params': None, 'f1': -1.0}\n",
    "    for params in gbm_grid:\n",
    "        res = run_loso(\n",
    "            sessions, verbose=False,\n",
    "            conf_threshold=conf_threshold, tmpl_threshold=tmpl_threshold,\n",
    "            gbm_params=params)\n",
    "        f1 = res.get('fine_f1_macro', 0.0)\n",
    "        if verbose:\n",
    "            print(f'  params={params} -> F1={f1:.3f}')\n",
    "        if f1 > best['f1']:\n",
    "            best = {'params': params, 'f1': f1}\n",
    "    if verbose and best['params'] is not None:\n",
    "        print(f'Best GBM params: {best[\"params\"]} (F1={best[\"f1\"]:.3f})')\n",
    "    return best\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bd7b601e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Patch: robust handling for empty cycle windows in feature extraction/training\n",
    "def extract_all_features(t0, t1, A0, A1, om0, om1,\n",
    "                         paired0, paired1, template, fs):\n",
    "    features = []\n",
    "    dt = 1.0 / fs\n",
    "    for (s0, e0), (s1, e1) in zip(paired0, paired1):\n",
    "        phys = physics_features(t0, t1, A0, A1, om0, om1, s0, e0, s1, e1, fs)\n",
    "        fourier = cycle_fourier_features(A0, om0, s0, e0, fs)\n",
    "        cm = build_cycle_matrix(A0, A1, om0, om1, s0, e0, s1, e1,\n",
    "                                CONFIG['TARGET_LEN'])\n",
    "        svd_feat = compute_svd_features(cm, CONFIG['PCA_COMPONENTS'])\n",
    "        corr_mean, corr_min = template_correlation(cm, template)\n",
    "        tmpl_feat = np.array([corr_mean, corr_min])\n",
    "        si_feat = subject_invariant_features(t0, t1, A0, A1, om0, om1,\n",
    "                                             s0, e0, s1, e1, fs)\n",
    "        feat = np.concatenate([phys, fourier, svd_feat, tmpl_feat,\n",
    "                               si_feat])\n",
    "        features.append(feat)\n",
    "\n",
    "    if len(features) == 0:\n",
    "        return np.empty((0, N_FEAT))\n",
    "    return np.vstack(features)\n",
    "\n",
    "\n",
    "def train_model(session_list, verbose=True, gbm_params=None):\n",
    "    \"\"\"\n",
    "    Train multi-class GBM from 5-tuple entries (homogeneous + heterogeneous).\n",
    "    Skips entries that produce zero valid cycles after windowing/filtering.\n",
    "    \"\"\"\n",
    "    fs = CONFIG['FS']\n",
    "    all_cms, all_sessions, all_labels, all_dnames = [], [], [], []\n",
    "\n",
    "    for entry in session_list:\n",
    "        d0, d1, label, dname, tw = entry\n",
    "        sess = _load_entry(entry)\n",
    "        all_sessions.append(sess)\n",
    "        all_cms.extend(sess['cycle_matrices'])\n",
    "        all_labels.append(label)\n",
    "        all_dnames.append(dname)\n",
    "        if verbose:\n",
    "            print(f'  {label:<22s} [{dname}]: {len(sess[\"paired0\"])} cycles')\n",
    "\n",
    "    if not all_cms:\n",
    "        raise ValueError('No cycles found — check processed data paths.')\n",
    "\n",
    "    template = build_template(all_cms)\n",
    "\n",
    "    class_cms = defaultdict(list)\n",
    "    for sess, lbl in zip(all_sessions, all_labels):\n",
    "        class_cms[lbl].extend(sess['cycle_matrices'])\n",
    "    class_templates = {lbl: build_template(cms) for lbl, cms in class_cms.items() if len(cms) > 0}\n",
    "\n",
    "    X_list, y_list, sid_list = [], [], []\n",
    "    kept = 0\n",
    "    for si, (sess, lbl, dname) in enumerate(zip(all_sessions, all_labels, all_dnames)):\n",
    "        X = extract_all_features(\n",
    "            sess['t0'], sess['t1'], sess['A0'], sess['A1'],\n",
    "            sess['om0'], sess['om1'], sess['paired0'], sess['paired1'],\n",
    "            template, fs)\n",
    "        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "\n",
    "        if X.shape[0] == 0:\n",
    "            if verbose:\n",
    "                print(f'    Skipping empty entry: {dname} ({lbl})')\n",
    "            continue\n",
    "\n",
    "        X_list.append(X)\n",
    "        y_list.extend([lbl] * len(X))\n",
    "        sid_list.extend([si] * len(X))\n",
    "        kept += 1\n",
    "\n",
    "    if not X_list:\n",
    "        raise ValueError('All training entries produced zero valid cycles after filtering.')\n",
    "\n",
    "    X_all   = np.vstack(X_list)\n",
    "    y_all   = np.array(y_list)\n",
    "    sid_all = np.array(sid_list)\n",
    "\n",
    "    scaler  = StandardScaler()\n",
    "    X_s     = scaler.fit_transform(X_all)\n",
    "    le      = LabelEncoder()\n",
    "    y_enc   = le.fit_transform(y_all)\n",
    "\n",
    "    gbm_params = {} if gbm_params is None else dict(gbm_params)\n",
    "    params = {\n",
    "        'n_estimators': 300,\n",
    "        'max_depth': 3,\n",
    "        'learning_rate': 0.05,\n",
    "        'random_state': 42,\n",
    "    }\n",
    "    params.update(gbm_params)\n",
    "    clf = GradientBoostingClassifier(**params)\n",
    "    clf.fit(X_s, y_enc)\n",
    "\n",
    "    if verbose:\n",
    "        print(f'\\nTrained on {X_all.shape[0]} cycles x {X_all.shape[1]} features')\n",
    "        print(f'Classes: {list(le.classes_)}')\n",
    "        print(f'Entries kept: {kept}/{len(session_list)}')\n",
    "        print(f'GBM params: {params}')\n",
    "\n",
    "    return {\n",
    "        'clf': clf, 'scaler': scaler, 'label_encoder': le,\n",
    "        'template': template, 'class_templates': class_templates,\n",
    "        'feature_names': ALL_FEAT_NAMES,\n",
    "        'X_train': X_all, 'y_train': y_all, 'session_ids': sid_all,\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e98b6f6c",
   "metadata": {},
   "source": [
    "---\n",
    "## 2b. Topology + shape PCA features\n",
    "\n",
    "**14D topology features** capture 3D trajectory shape that scalar features miss:\n",
    "- Cross-axis phase lags normalized by dominant period (T_dom)\n",
    "- Plane and spatial ratios (σ₂/σ₁ and σ₃/σ₁ from 3-axis gyro SVD)\n",
    "- Invariant winding (zero-crossings per cycle for ωx and ωy)\n",
    "\n",
    "**Shape PCA (top-k)** preserves temporal waveform structure:\n",
    "- Flatten 12×64 cycle matrix to 768D, fit PCA on training data, keep top-k for 96% variance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8d51cdb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════════\n",
    "# Topology features — capture 3D trajectory shape\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def topology_features(om0, om1, s0, e0, s1, e1, fs):\n",
    "    \"\"\"Enhanced topology features with sneak-sensitive dynamic descriptors.\"\"\"\n",
    "    feats = []\n",
    "\n",
    "    def _phase_lag_deg(a, b, t_ref):\n",
    "        a_c, b_c = a - np.mean(a), b - np.mean(b)\n",
    "        corr = np.correlate(a_c, b_c, mode='full')\n",
    "        lag_samples = np.argmax(corr) - (len(a) - 1)\n",
    "        phase_deg = (lag_samples / max(1.0, t_ref)) * 360.0\n",
    "        return np.abs((phase_deg + 180.0) % 360.0 - 180.0)\n",
    "\n",
    "    for w_raw in [om0[s0:e0], om1[s1:e1]]:\n",
    "        w = w_raw.copy()\n",
    "        n = len(w)\n",
    "        if n < 6:\n",
    "            feats.extend([0.0] * 19)\n",
    "            continue\n",
    "\n",
    "        wx, wy, wz = w[:, 0], w[:, 1], w[:, 2]\n",
    "\n",
    "        # ---------- 1. Dominant period ----------\n",
    "        w_norm = np.linalg.norm(w, axis=1)\n",
    "        w_norm_c = w_norm - np.mean(w_norm)\n",
    "        acorr = np.correlate(w_norm_c, w_norm_c, mode='full')[n-1:]\n",
    "        min_lag = max(2, int(CONFIG['CYCLE_MIN_PERIOD_S'] * fs))\n",
    "        max_lag = min(n - 2, int(CONFIG['CYCLE_MAX_PERIOD_S'] * fs))\n",
    "        if max_lag > min_lag:\n",
    "            ac_seg = acorr[min_lag:max_lag + 1]\n",
    "            prom = max(1e-12, 0.05 * acorr[0])\n",
    "            peaks, props = find_peaks(ac_seg, prominence=prom)\n",
    "            if len(peaks) > 0:\n",
    "                best = peaks[np.argmax(props['prominences'])]\n",
    "                T_dom = float(min_lag + best)\n",
    "            else:\n",
    "                T_dom = float(max(1, n))\n",
    "        else:\n",
    "            T_dom = float(max(1, n))\n",
    "\n",
    "        # ---------- 2. Cross-axis phase lags ----------\n",
    "        phase_xy = _phase_lag_deg(wx, wy, T_dom)\n",
    "        phase_xz = _phase_lag_deg(wx, wz, T_dom)\n",
    "        phase_yz = _phase_lag_deg(wy, wz, T_dom)\n",
    "        feats.extend([phase_xy, phase_xz, phase_yz])\n",
    "\n",
    "        # ---------- 3. SVD spatial ratios ----------\n",
    "        _, S_w, _ = np.linalg.svd(w.T, full_matrices=False)\n",
    "        if len(S_w) >= 3:\n",
    "            s_sum = S_w[0] + 1e-12\n",
    "            feats.append(S_w[1] / s_sum)  # planarity\n",
    "            feats.append(S_w[2] / s_sum)  # spatial complexity\n",
    "        else:\n",
    "            feats.extend([0.0, 0.0])\n",
    "\n",
    "        # ---------- 4. Winding numbers ----------\n",
    "        cycles = max(1.0, n / T_dom)\n",
    "        wx_zc = np.sum(np.diff(np.sign(wx - np.mean(wx))) != 0)\n",
    "        wy_zc = np.sum(np.diff(np.sign(wy - np.mean(wy))) != 0)\n",
    "        feats.extend([wx_zc / cycles, wy_zc / cycles])\n",
    "\n",
    "        # ---------- 5. Axis energy distribution ----------\n",
    "        energy = np.array([np.mean(wx**2), np.mean(wy**2), np.mean(wz**2)])\n",
    "        energy /= (np.sum(energy) + 1e-12)\n",
    "        feats.extend(energy.tolist())\n",
    "\n",
    "        # ---------- 6. Torsion + variability ----------\n",
    "        v_shift = np.roll(w, -1, axis=0)\n",
    "        cross_mag = np.linalg.norm(np.cross(w[:-1], v_shift[:-1]), axis=1)\n",
    "        torsion = float(np.mean(cross_mag)) if len(cross_mag) else 0.0\n",
    "        torsion_var = float(np.var(cross_mag)) if len(cross_mag) > 1 else 0.0\n",
    "        feats.extend([torsion, torsion_var])\n",
    "\n",
    "        # ---------- 7. Temporal variability ----------\n",
    "        temporal_var = float(np.var(w_norm))\n",
    "\n",
    "        # Phase variability in short windows (sneak sensitivity)\n",
    "        phase_win = max(6, int(0.5 * T_dom))\n",
    "        phase_step = max(1, phase_win // 2)\n",
    "        phase_xy_vals, phase_yz_vals = [], []\n",
    "        if phase_win < n:\n",
    "            for st in range(0, n - phase_win + 1, phase_step):\n",
    "                swx = wx[st:st + phase_win]\n",
    "                swy = wy[st:st + phase_win]\n",
    "                swz = wz[st:st + phase_win]\n",
    "                phase_xy_vals.append(_phase_lag_deg(swx, swy, T_dom))\n",
    "                phase_yz_vals.append(_phase_lag_deg(swy, swz, T_dom))\n",
    "        phase_xy_var = float(np.var(phase_xy_vals)) if len(phase_xy_vals) > 1 else 0.0\n",
    "        phase_yz_var = float(np.var(phase_yz_vals)) if len(phase_yz_vals) > 1 else 0.0\n",
    "\n",
    "        # Local nonstationarity: variance of short-window temporal variance\n",
    "        local_win = max(6, int(0.25 * T_dom))\n",
    "        local_step = max(1, local_win // 2)\n",
    "        local_vars = []\n",
    "        if local_win < n:\n",
    "            for st in range(0, n - local_win + 1, local_step):\n",
    "                local_vars.append(np.var(w_norm[st:st + local_win]))\n",
    "        local_temporal_var = float(np.var(local_vars)) if len(local_vars) > 1 else 0.0\n",
    "        rolling_var_mean = float(np.mean(local_vars)) if len(local_vars) > 0 else 0.0\n",
    "        temporal_var_deriv = float(np.mean(np.abs(np.diff(local_vars)))) if len(local_vars) > 1 else 0.0\n",
    "        phase_xy_drift = float(np.mean(np.abs(np.diff(phase_xy_vals)))) if len(phase_xy_vals) > 1 else 0.0\n",
    "        phase_yz_drift = float(np.mean(np.abs(np.diff(phase_yz_vals)))) if len(phase_yz_vals) > 1 else 0.0\n",
    "        phase_drift = 0.5 * (phase_xy_drift + phase_yz_drift)\n",
    "\n",
    "        feats.extend([\n",
    "            temporal_var, phase_xy_var, phase_yz_var, local_temporal_var,\n",
    "            rolling_var_mean, temporal_var_deriv, phase_drift\n",
    "        ])\n",
    "\n",
    "    return np.array(feats)\n",
    "\n",
    "TOPO_FEAT_NAMES = []\n",
    "for dev in ['d0', 'd1']:\n",
    "    TOPO_FEAT_NAMES += [\n",
    "        f'phase_xy_{dev}', f'phase_xz_{dev}', f'phase_yz_{dev}',\n",
    "        f'plane_ratio_2_1_{dev}', f'spatial_ratio_3_1_{dev}',\n",
    "        f'wind_wx_{dev}', f'wind_wy_{dev}',\n",
    "        f'energy_x_{dev}', f'energy_y_{dev}', f'energy_z_{dev}',\n",
    "        f'torsion_{dev}', f'torsion_var_{dev}',\n",
    "        f'temporal_var_{dev}', f'phase_xy_var_{dev}', f'phase_yz_var_{dev}',\n",
    "        f'local_temporal_var_{dev}',\n",
    "        f'rolling_var_{dev}', f'temporal_var_deriv_{dev}', f'phase_drift_{dev}'\n",
    "    ]\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# Cycle-matrix PCA shape features\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "N_PCA_SHAPE_MAX = None  # no artificial cap; rely on variance target + data rank\n",
    "SHAPE_PCA_VAR_TARGET = 0.96\n",
    "SHAPE_PCA_NAME_PREFIX = 'shape_pc_'\n",
    "PAIRWISE_EPS = 1e-6\n",
    "PAIRWISE_FEATURE_NAMES = [\n",
    "    'pair_wind_wy_wx_ratio_d0',\n",
    "    'pair_phase_xz_xy_absdiff_d0',\n",
    "    'pair_spatial_minus_plane_d0',\n",
    "    'pair_local_temporal_ratio_d0',\n",
    "    'pair_phase_yz_d0d1_absdiff',\n",
    "    'pair_torsion_var_ratio_d0',\n",
    "]\n",
    "STABLE_PCA_COMPONENTS = [4, 25, 27, 33, 34, 35, 42, 43, 47, 49, 50]\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "# Override feature names and extraction\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "FULL_BASE_FEAT_NAMES = (PHYSICS_NAMES + FOURIER_NAMES + SVD_NAMES + TEMPLATE_NAMES\n",
    "                        + DMD_FEAT_NAMES + SI_FEAT_NAMES + TOPO_FEAT_NAMES)\n",
    "SELECTED_BASE_FEATURES = [\n",
    "    'phase_xy_d0', 'phase_xz_d0', 'phase_yz_d0',\n",
    "    'phase_xy_d1', 'phase_xz_d1', 'phase_yz_d1',\n",
    "    'plane_ratio_2_1_d0', 'spatial_ratio_3_1_d0',\n",
    "    'wind_wx_d0', 'wind_wy_d0',\n",
    "    'torsion_d0', 'temporal_var_d0',\n",
    "    'torsion_var_d0', 'phase_xy_var_d0', 'phase_yz_var_d0', 'local_temporal_var_d0',\n",
    "    'rolling_var_d0', 'temporal_var_deriv_d0', 'phase_drift_d0',\n",
    "]\n",
    "missing_selected = [f for f in SELECTED_BASE_FEATURES if f not in FULL_BASE_FEAT_NAMES]\n",
    "if missing_selected:\n",
    "    raise ValueError(f'Missing selected base features: {missing_selected}')\n",
    "SELECTED_BASE_IDX = [FULL_BASE_FEAT_NAMES.index(f) for f in SELECTED_BASE_FEATURES]\n",
    "BASE_FEAT_NAMES = SELECTED_BASE_FEATURES + PAIRWISE_FEATURE_NAMES\n",
    "N_FULL_BASE_FEAT = len(FULL_BASE_FEAT_NAMES)\n",
    "N_BASE_FEAT = len(BASE_FEAT_NAMES)\n",
    "ALL_FEAT_NAMES = BASE_FEAT_NAMES.copy()\n",
    "print(f'Full base feature dimension: {N_FULL_BASE_FEAT}D')\n",
    "print(f'Selected base feature dimension (before shape PCA): {N_BASE_FEAT}D')\n",
    "\n",
    "MIN_CYCLES_PER_ENTRY = 5\n",
    "\n",
    "def build_pairwise_features(X_base_selected, eps=PAIRWISE_EPS):\n",
    "    \"\"\"Targeted pairwise features for known weak class boundaries.\"\"\"\n",
    "    if X_base_selected.ndim != 2 or X_base_selected.shape[0] == 0:\n",
    "        return np.empty((0, len(PAIRWISE_FEATURE_NAMES)))\n",
    "    idx = {n: i for i, n in enumerate(SELECTED_BASE_FEATURES)}\n",
    "    wy = X_base_selected[:, idx['wind_wy_d0']]\n",
    "    wx = X_base_selected[:, idx['wind_wx_d0']]\n",
    "    phase_xz = X_base_selected[:, idx['phase_xz_d0']]\n",
    "    phase_xy = X_base_selected[:, idx['phase_xy_d0']]\n",
    "    spatial = X_base_selected[:, idx['spatial_ratio_3_1_d0']]\n",
    "    planar = X_base_selected[:, idx['plane_ratio_2_1_d0']]\n",
    "    local_tvar = X_base_selected[:, idx['local_temporal_var_d0']]\n",
    "    tvar = X_base_selected[:, idx['temporal_var_d0']]\n",
    "    phase_yz_d0 = X_base_selected[:, idx['phase_yz_d0']]\n",
    "    phase_yz_d1 = X_base_selected[:, idx['phase_yz_d1']]\n",
    "    torsion_var = X_base_selected[:, idx['torsion_var_d0']]\n",
    "    torsion = X_base_selected[:, idx['torsion_d0']]\n",
    "    return np.column_stack([\n",
    "        wy / (wx + eps),\n",
    "        np.abs(phase_xz - phase_xy),\n",
    "        spatial - planar,\n",
    "        local_tvar / (tvar + eps),\n",
    "        np.abs(phase_yz_d0 - phase_yz_d1),\n",
    "        torsion_var / (np.abs(torsion) + eps),\n",
    "    ])\n",
    "\n",
    "def extract_features(t0, t1, A0, A1, om0, om1,\n",
    "                          paired0, paired1, template, fs,\n",
    "                          shape_pca=None, shape_pca_n_components=None,\n",
    "                          shape_pca_indices=None, selected_base_idx=None):\n",
    "    \"\"\"Extract features with optional dynamic-k shape PCA tail.\"\"\"\n",
    "    features = []\n",
    "    flat_matrices = []\n",
    "    dt = 1.0 / fs\n",
    "    for (s0, e0), (s1, e1) in zip(paired0, paired1):\n",
    "        phys = physics_features(t0, t1, A0, A1, om0, om1, s0, e0, s1, e1, fs)\n",
    "        fourier = cycle_fourier_features(A0, om0, s0, e0, fs)\n",
    "        cm = build_cycle_matrix(A0, A1, om0, om1, s0, e0, s1, e1, CONFIG['TARGET_LEN'])\n",
    "        svd_feat = compute_svd_features(cm, CONFIG['PCA_COMPONENTS'])\n",
    "        corr_mean, corr_min = template_correlation(cm, template)\n",
    "        tmpl_feat = np.array([corr_mean, corr_min])\n",
    "        dmd_feat = dmd_features(cm, dt)\n",
    "        si_feat = subject_invariant_features(t0, t1, A0, A1, om0, om1, s0, e0, s1, e1, fs)\n",
    "        topo = topology_features(om0, om1, s0, e0, s1, e1, fs)\n",
    "        feat = np.concatenate([phys, fourier, svd_feat, tmpl_feat,\n",
    "                               dmd_feat, si_feat, topo])\n",
    "        features.append(feat)\n",
    "        flat_matrices.append(cm.ravel())\n",
    "    X = np.array(features) if features else np.empty((0, len(FULL_BASE_FEAT_NAMES)))\n",
    "    if selected_base_idx is not None:\n",
    "        if len(X) > 0:\n",
    "            X = X[:, selected_base_idx]\n",
    "        else:\n",
    "            X = np.empty((0, len(selected_base_idx)))\n",
    "        pairwise = build_pairwise_features(X)\n",
    "        if len(X) > 0:\n",
    "            X = np.hstack([X, pairwise])\n",
    "        else:\n",
    "            X = np.empty((0, len(BASE_FEAT_NAMES)))\n",
    "    flat_mat = np.array(flat_matrices) if flat_matrices else np.empty((0, 12 * CONFIG['TARGET_LEN']))\n",
    "    if shape_pca is not None and len(flat_mat) > 0:\n",
    "        pca_scores_all = shape_pca.transform(flat_mat)\n",
    "        if shape_pca_indices is not None:\n",
    "            idx = [int(i) for i in shape_pca_indices if int(i) < pca_scores_all.shape[1]]\n",
    "            if not idx:\n",
    "                n_comp = shape_pca.n_components_ if shape_pca_n_components is None else shape_pca_n_components\n",
    "                n_comp = max(1, min(int(n_comp), pca_scores_all.shape[1]))\n",
    "                idx = list(range(n_comp))\n",
    "            pca_scores = pca_scores_all[:, idx]\n",
    "        else:\n",
    "            n_comp = shape_pca.n_components_ if shape_pca_n_components is None else shape_pca_n_components\n",
    "            n_comp = max(1, min(int(n_comp), pca_scores_all.shape[1]))\n",
    "            pca_scores = pca_scores_all[:, :n_comp]\n",
    "        X = np.hstack([X, pca_scores])\n",
    "    return X, flat_mat\n",
    "\n",
    "\n",
    "# Override extract_all_features\n",
    "def extract_all_features(t0, t1, A0, A1, om0, om1,\n",
    "                         paired0, paired1, template, fs):\n",
    "    \"\"\"Wrapper for backward compatibility — without PCA.\"\"\"\n",
    "    X, _ = extract_features(t0, t1, A0, A1, om0, om1,\n",
    "                                 paired0, paired1, template, fs,\n",
    "                                 shape_pca=None,\n",
    "                                 selected_base_idx=SELECTED_BASE_IDX)\n",
    "    return X\n",
    "\n",
    "\n",
    "# Override train_model to use features + min-cycle filter + PCA\n",
    "_orig_train = train_model\n",
    "\n",
    "def train_model(session_list, verbose=True, gbm_params=None):\n",
    "    \"\"\"Enhanced training: min-cycle filter + shape PCA.\"\"\"\n",
    "    from sklearn.decomposition import PCA as _PCA\n",
    "    fs = CONFIG['FS']\n",
    "    all_sessions, all_labels, all_dnames = [], [], []\n",
    "    skipped = 0\n",
    "\n",
    "    for entry in session_list:\n",
    "        d0, d1, label, dname, tw = entry\n",
    "        sess = _load_entry(entry)\n",
    "        n_cycles = len(sess['paired0'])\n",
    "        if n_cycles < MIN_CYCLES_PER_ENTRY:\n",
    "            if verbose:\n",
    "                print(f'  SKIP {label:<22s} [{dname}]: {n_cycles} cyc (< {MIN_CYCLES_PER_ENTRY})')\n",
    "            skipped += 1\n",
    "            continue\n",
    "        all_sessions.append(sess)\n",
    "        all_labels.append(label)\n",
    "        all_dnames.append(dname)\n",
    "        if verbose:\n",
    "            print(f'  {label:<22s} [{dname}]: {n_cycles} cycles')\n",
    "\n",
    "    if verbose and skipped:\n",
    "        print(f'  ({skipped} entries skipped)')\n",
    "\n",
    "    all_cms = []\n",
    "    for sess in all_sessions:\n",
    "        all_cms.extend(sess['cycle_matrices'])\n",
    "    if not all_cms:\n",
    "        raise ValueError('No cycles found.')\n",
    "\n",
    "    template = build_template(all_cms)\n",
    "    class_cms = defaultdict(list)\n",
    "    for sess, lbl in zip(all_sessions, all_labels):\n",
    "        class_cms[lbl].extend(sess['cycle_matrices'])\n",
    "    class_templates = {lbl: build_template(cms) for lbl, cms in class_cms.items()}\n",
    "\n",
    "    # Extract features (without PCA first)\n",
    "    X_list, flat_list, y_list, sid_list = [], [], [], []\n",
    "    for si, (sess, lbl) in enumerate(zip(all_sessions, all_labels)):\n",
    "        X, flat = extract_features(\n",
    "            sess['t0'], sess['t1'], sess['A0'], sess['A1'],\n",
    "            sess['om0'], sess['om1'], sess['paired0'], sess['paired1'],\n",
    "            template, fs, shape_pca=None,\n",
    "            selected_base_idx=SELECTED_BASE_IDX)\n",
    "        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "        X_list.append(X)\n",
    "        flat_list.append(flat)\n",
    "        y_list.extend([lbl] * len(X))\n",
    "        sid_list.extend([si] * len(X))\n",
    "\n",
    "    X_base = np.vstack(X_list)\n",
    "    flat_all = np.vstack(flat_list) if flat_list else np.empty((0, 768))\n",
    "    y_all = np.array(y_list)\n",
    "    sid_all = np.array(sid_list)\n",
    "\n",
    "    # Fit shape PCA and keep top-k PCs capturing target variance\n",
    "    pca_cap = min(max(1, flat_all.shape[0] - 1), flat_all.shape[1])\n",
    "    shape_pca = _PCA(n_components=pca_cap, svd_solver='full')\n",
    "    pca_scores = shape_pca.fit_transform(flat_all)\n",
    "    cumvar = np.cumsum(shape_pca.explained_variance_ratio_)\n",
    "    n_use = int(np.searchsorted(cumvar, SHAPE_PCA_VAR_TARGET) + 1)\n",
    "    n_use = max(1, min(n_use, pca_scores.shape[1]))\n",
    "    achieved_cumvar = float(cumvar[n_use - 1])\n",
    "    pca_keep_idx = [i for i in STABLE_PCA_COMPONENTS if i < n_use]\n",
    "    if not pca_keep_idx:\n",
    "        pca_keep_idx = list(range(n_use))\n",
    "    pca_scores_keep = pca_scores[:, pca_keep_idx]\n",
    "    X_all = np.hstack([X_base, pca_scores_keep])\n",
    "    feature_names = BASE_FEAT_NAMES + [f'{SHAPE_PCA_NAME_PREFIX}{i}' for i in pca_keep_idx]\n",
    "\n",
    "    # Per-session normalization to reduce subject/session scale shifts\n",
    "    for si in np.unique(sid_all):\n",
    "        mask = (sid_all == si)\n",
    "        Xi = X_all[mask]\n",
    "        mu = np.mean(Xi, axis=0, keepdims=True)\n",
    "        sd = np.std(Xi, axis=0, keepdims=True)\n",
    "        X_all[mask] = (Xi - mu) / (sd + 1e-6)\n",
    "\n",
    "    scaler = StandardScaler()\n",
    "    X_s = scaler.fit_transform(X_all)\n",
    "    le = LabelEncoder()\n",
    "    y_enc = le.fit_transform(y_all)\n",
    "\n",
    "    class_counts = Counter(y_all.tolist())\n",
    "    class_weights = {\n",
    "        cls: len(y_all) / (len(class_counts) * cnt)\n",
    "        for cls, cnt in class_counts.items()\n",
    "    }\n",
    "    sample_weight = np.array([class_weights[y] for y in y_all], dtype=float)\n",
    "\n",
    "    params = gbm_params or {'n_estimators': 350, 'max_depth': 4,\n",
    "                             'learning_rate': 0.05}\n",
    "    clf = GradientBoostingClassifier(**params, random_state=42)\n",
    "    clf.fit(X_s, y_enc, sample_weight=sample_weight)\n",
    "\n",
    "    if verbose:\n",
    "        print(f'\\nTrained on {X_all.shape[0]} cycles x {X_all.shape[1]} features')\n",
    "        print(f'Classes: {list(le.classes_)}')\n",
    "        print('Class distribution (cycles):')\n",
    "        for cls, cnt in sorted(class_counts.items()):\n",
    "            print(f'  {cls:<22s}: {cnt:>5d} (w={class_weights[cls]:.3f})')\n",
    "        print(f'Shape PCA components needed for target variance: {n_use} (target variance={SHAPE_PCA_VAR_TARGET:.2f})')\n",
    "        print(f'Shape PCA components kept after stability pruning: {len(pca_keep_idx)} -> {pca_keep_idx}')\n",
    "        print(f'Achieved cumulative variance at n_use: {achieved_cumvar:.4f}')\n",
    "\n",
    "    return {\n",
    "        'clf': clf, 'scaler': scaler, 'label_encoder': le,\n",
    "        'template': template, 'class_templates': class_templates,\n",
    "        'shape_pca': shape_pca,\n",
    "        'shape_pca_n_components': len(pca_keep_idx),\n",
    "        'shape_pca_target_n_components': n_use,\n",
    "        'shape_pca_indices': pca_keep_idx,\n",
    "        'shape_pca_cumvar': achieved_cumvar,\n",
    "        'class_distribution': dict(class_counts),\n",
    "        'class_weights': class_weights,\n",
    "        'selected_base_idx': SELECTED_BASE_IDX,\n",
    "        'feature_names': feature_names,\n",
    "        'X_train': X_all, 'y_train': y_all, 'session_ids': sid_all,\n",
    "    }\n",
    "\n",
    "\n",
    "# Override classify_session to use shape PCA from model\n",
    "_orig_classify = classify_session\n",
    "\n",
    "def classify_session(path_d0, path_d1, model, time_windows=None, verbose=True,\n",
    "                          conf_threshold=None, tmpl_threshold=None):\n",
    "    \"\"\"Enhanced classify: uses shape PCA.\"\"\"\n",
    "    fs = CONFIG['FS']\n",
    "    sess = (process_session(path_d0, path_d1) if time_windows is None\n",
    "            else process_session_windowed(path_d0, path_d1, time_windows))\n",
    "\n",
    "    if not sess['paired0']:\n",
    "        return {'labels': [], 'confidences': [], 'X': np.array([]),\n",
    "                'verdict': 'unknown', 'vote': {}, 'n_transition': 0, 'session': sess}\n",
    "\n",
    "    X, flat = extract_features(\n",
    "        sess['t0'], sess['t1'], sess['A0'], sess['A1'],\n",
    "        sess['om0'], sess['om1'], sess['paired0'], sess['paired1'],\n",
    "        model['template'], fs,\n",
    "        shape_pca=model.get('shape_pca'),\n",
    "        shape_pca_n_components=model.get('shape_pca_n_components'),\n",
    "        shape_pca_indices=model.get('shape_pca_indices'),\n",
    "        selected_base_idx=model.get('selected_base_idx', SELECTED_BASE_IDX))\n",
    "    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "    if X.ndim == 2 and len(X) > 0:\n",
    "        X = (X - np.mean(X, axis=0, keepdims=True)) / (np.std(X, axis=0, keepdims=True) + 1e-6)\n",
    "\n",
    "    if X.ndim < 2 or len(X) == 0:\n",
    "        return {'labels': [], 'confidences': [], 'X': np.empty((0, len(model['feature_names']))),\n",
    "                'verdict': 'unknown', 'vote': {}, 'n_transition': 0, 'session': sess}\n",
    "\n",
    "    X_s = model['scaler'].transform(X)\n",
    "\n",
    "    le = model['label_encoder']\n",
    "    y_pred_enc = model['clf'].predict(X_s)\n",
    "    y_pred_proba = model['clf'].predict_proba(X_s)\n",
    "    pred_labels = le.inverse_transform(y_pred_enc)\n",
    "    confidences = np.max(y_pred_proba, axis=1)\n",
    "\n",
    "    ct = conf_threshold or CONFIG['CONFIDENCE_THRESHOLD']\n",
    "    tt = tmpl_threshold or CONFIG['TEMPLATE_GATE_THRESHOLD']\n",
    "\n",
    "    conf_gate = confidences >= ct\n",
    "    tmpl_gate = np.zeros(len(X), dtype=bool)\n",
    "    for ci in range(len(X)):\n",
    "        cm = build_cycle_matrix(\n",
    "            sess['A0'], sess['A1'], sess['om0'], sess['om1'],\n",
    "            sess['paired0'][ci][0], sess['paired0'][ci][1],\n",
    "            sess['paired1'][ci][0], sess['paired1'][ci][1],\n",
    "            CONFIG['TARGET_LEN'])\n",
    "        for cls_tmpl in model['class_templates'].values():\n",
    "            if template_correlation(cm, cls_tmpl)[0] >= tt:\n",
    "                tmpl_gate[ci] = True\n",
    "                break\n",
    "\n",
    "    labels = [pred_labels[i] if (conf_gate[i] and tmpl_gate[i]) else 'transition'\n",
    "              for i in range(len(X))]\n",
    "\n",
    "    non_trans = [l for l in labels if l != 'transition']\n",
    "    vote = Counter(non_trans) if non_trans else Counter(labels)\n",
    "    verdict = vote.most_common(1)[0][0] if non_trans else 'unknown'\n",
    "\n",
    "    if verbose:\n",
    "        print(f'  {len(labels)} cycles | ', end='')\n",
    "        for cls, cnt in sorted(Counter(labels).items()):\n",
    "            print(f'{cls}={cnt} ', end='')\n",
    "        print(f'-> {verdict}')\n",
    "\n",
    "    return {\n",
    "        'labels': labels, 'confidences': confidences.tolist(), 'X': X,\n",
    "        'verdict': verdict, 'vote': dict(Counter(non_trans)),\n",
    "        'n_transition': sum(1 for l in labels if l == 'transition'),\n",
    "        'session': sess,\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f42068dd",
   "metadata": {},
   "source": [
    "---\n",
    "## 4. Session discovery"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bc9a825",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Discover all sessions ─────────────────────────────────────────────\n",
    "ALL_SESSIONS = discover_all_sessions(DATA_PROCESSED)\n",
    "by_class = summarize_sessions(ALL_SESSIONS)\n",
    "\n",
    "print(f'\\nHomogeneous entries  : {sum(1 for e in ALL_SESSIONS if e[4] is None)}')\n",
    "print(f'Heterogeneous entries: {sum(1 for e in ALL_SESSIONS if e[4] is not None)}')\n",
    "print(f'Total                : {len(ALL_SESSIONS)}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "16e7adfb",
   "metadata": {},
   "source": [
    "### 4.1 Timestamp alignment check"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "367e3f8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Verify JSON timestamps match CSV timestamps ─────────────────────\n",
    "hetero = [e for e in ALL_SESSIONS if e[4] is not None]\n",
    "if hetero:\n",
    "    print(f'Checking timestamp alignment for {len(hetero)} heterogeneous entries...')\n",
    "    mismatches = 0\n",
    "    for e in hetero[:5]:  # check first 5\n",
    "        d0 = pd.read_csv(e[0])\n",
    "        csv_end = d0['timestamp_ms'].iloc[-1] / 1000\n",
    "        json_max = max(w[1] for w in e[4])\n",
    "        ok = json_max <= csv_end * 1.1  # allow 10% tolerance\n",
    "        status = 'OK' if ok else 'MISMATCH'\n",
    "        if not ok:\n",
    "            mismatches += 1\n",
    "        print(f'  {e[3]:<50s} CSV=[0, {csv_end:.1f}s] JSON_max={json_max:.1f}s [{status}]')\n",
    "    if mismatches > 0:\n",
    "        print(f'\\nWARNING: {mismatches} timestamp mismatches detected!')\n",
    "        print('JSON may use absolute timestamps — offset correction needed.')\n",
    "    else:\n",
    "        print('\\nAll timestamps aligned.')\n",
    "else:\n",
    "    print('No heterogeneous sessions found.')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "61d0938e",
   "metadata": {},
   "source": [
    "---\n",
    "## 5. Stratified train / test split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12a11f3f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Stratified train/test split (~80/20 by recording group) ──────────\n",
    "import time as _time\n",
    "SPLIT_SEED = int(_time.time()) % 10000\n",
    "TRAIN_SESSIONS, TEST_SESSIONS = stratified_group_split(ALL_SESSIONS, test_fraction=0.2, min_train_fraction=0.8, random_state=SPLIT_SEED)\n",
    "print(f'Split seed: {SPLIT_SEED}')\n",
    "\n",
    "print(f'Train entries : {len(TRAIN_SESSIONS)}')\n",
    "print(f'Test  entries : {len(TEST_SESSIONS)}')\n",
    "print()\n",
    "train_classes = Counter(e[2] for e in TRAIN_SESSIONS)\n",
    "test_classes  = Counter(e[2] for e in TEST_SESSIONS)\n",
    "print(f'  {\"Class\":<22s}  {\"Train\":>6s}  {\"Test\":>6s}')\n",
    "for cls in sorted(set(list(train_classes) + list(test_classes))):\n",
    "    print(f'  {cls:<22s}  {train_classes.get(cls,0):>6d}  {test_classes.get(cls,0):>6d}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "35f20f6e",
   "metadata": {},
   "source": [
    "---\n",
    "## 6. LOSO cross-validation (training set)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe1f08b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── LOSO cross-validation on training set ────────────────────────────\n",
    "# Optional tuning: small grid search for GBM params + thresholds\n",
    "TUNE_MODEL = False\n",
    "GBM_GRID = [\n",
    "    {'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.1},\n",
    "    {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.05},\n",
    "    {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.05},\n",
    "    {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.1, 'subsample': 0.8},\n",
    "]\n",
    "CONF_GRID = [0.5, 0.6, 0.7, 0.8]\n",
    "TMPL_GRID = [0.1, 0.2, 0.3]\n",
    "BEST_GBM = None\n",
    "BEST_GBM_PARAMS = None\n",
    "if TUNE_MODEL:\n",
    "    print('Tuning GBM params (LOSO)...')\n",
    "    BEST_GBM = tune_gbm_params(\n",
    "        TRAIN_SESSIONS, GBM_GRID,\n",
    "        conf_threshold=CONFIG['CONFIDENCE_THRESHOLD'],\n",
    "        tmpl_threshold=CONFIG['TEMPLATE_GATE_THRESHOLD'])\n",
    "    BEST_GBM_PARAMS = BEST_GBM['params'] if BEST_GBM else None\n",
    "    if BEST_GBM_PARAMS is not None:\n",
    "        print(f'Using GBM params: {BEST_GBM_PARAMS}')\n",
    "    print('\\nTuning thresholds (LOSO)...')\n",
    "    best_thr = tune_thresholds(\n",
    "        TRAIN_SESSIONS, CONF_GRID, TMPL_GRID,\n",
    "        gbm_params=BEST_GBM_PARAMS)\n",
    "    if best_thr['conf_threshold'] is not None:\n",
    "        CONFIG['CONFIDENCE_THRESHOLD'] = best_thr['conf_threshold']\n",
    "        CONFIG['TEMPLATE_GATE_THRESHOLD'] = best_thr['tmpl_threshold']\n",
    "        print(f'Applied thresholds: conf={CONFIG[\"CONFIDENCE_THRESHOLD\"]:.2f}, '\n",
    "              f'tmpl={CONFIG[\"TEMPLATE_GATE_THRESHOLD\"]:.2f}')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1466bdd6",
   "metadata": {},
   "outputs": [],
   "source": [
    "print('Running LOSO CV on training set…')\n",
    "print('='*80)\n",
    "loso_results = run_loso(\n",
    "    TRAIN_SESSIONS, verbose=True,\n",
    "    conf_threshold=CONFIG['CONFIDENCE_THRESHOLD'],\n",
    "    tmpl_threshold=CONFIG['TEMPLATE_GATE_THRESHOLD'],\n",
    "    gbm_params=BEST_GBM_PARAMS)\n",
    "print(f'\\nLOSO fine  F1 (macro): {loso_results.get(\"fine_f1_macro\", 0):.3f}')\n",
    "print(f'LOSO macro F1 (macro): {loso_results.get(\"macro_f1_macro\", 0):.3f}')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5ec0b02c",
   "metadata": {},
   "source": [
    "---\n",
    "## 7. Final model & held-out test evaluation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f36babd4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Final model trained on full training set ──────────────────────────\n",
    "print('Training final model on all training entries…')\n",
    "print('='*80)\n",
    "MODEL_FINAL = train_model(TRAIN_SESSIONS, verbose=True, gbm_params=BEST_GBM_PARAMS)\n",
    "\n",
    "# ── Held-out test evaluation ──────────────────────────────────────────\n",
    "print('\\n' + '='*80)\n",
    "print('Evaluating on held-out test set…')\n",
    "print('='*80)\n",
    "test_results = evaluate_test_set(\n",
    "    TEST_SESSIONS, MODEL_FINAL, verbose=True,\n",
    "    conf_threshold=CONFIG['CONFIDENCE_THRESHOLD'],\n",
    "    tmpl_threshold=CONFIG['TEMPLATE_GATE_THRESHOLD'])\n",
    "print(f'\\nTest  fine  F1 (macro): {test_results.get(\"test_f1_macro\", 0):.3f}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4bd1f234",
   "metadata": {},
   "source": [
    "---\n",
    "## 8. Diagnostics"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f95aca5b",
   "metadata": {},
   "source": [
    "### 8.1  Confusion matrices — LOSO vs test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "41c98b0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Confusion matrices ────────────────────────────────────────────────\n",
    "fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
    "for ax, res, title in zip(\n",
    "    axes,\n",
    "    [loso_results, test_results],\n",
    "    ['LOSO CV (train set)', 'Held-out test set']\n",
    "):\n",
    "    if 'fine_cm' not in res:\n",
    "        ax.set_title(f'{title} — no data'); continue\n",
    "    cm = res['fine_cm']\n",
    "    classes = res['fine_classes']\n",
    "    im = ax.imshow(cm, cmap='Blues')\n",
    "    ax.set_xticks(range(len(classes))); ax.set_yticks(range(len(classes)))\n",
    "    ax.set_xticklabels(classes, rotation=45, ha='right', fontsize=9)\n",
    "    ax.set_yticklabels(classes, fontsize=9)\n",
    "    for i in range(len(classes)):\n",
    "        for j in range(len(classes)):\n",
    "            ax.text(j, i, str(cm[i, j]), ha='center', va='center',\n",
    "                    color='white' if cm[i,j] > cm.max()*0.5 else 'black', fontsize=8)\n",
    "    ax.set_xlabel('Predicted'); ax.set_ylabel('True')\n",
    "    f1 = res.get('fine_f1_macro', res.get('test_f1_macro', 0))\n",
    "    ax.set_title(f'{title}\\nmacro-F1 = {f1:.3f}', fontsize=11)\n",
    "    plt.colorbar(im, ax=ax)\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(RESULTS_DIR, 'fig_confusion_matrices.png'), bbox_inches='tight')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5aeb21ad",
   "metadata": {},
   "source": [
    "### 8.2  LOSO vs test F1 comparison"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1782df07",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── LOSO vs Test F1 comparison bar chart ─────────────────────────────\n",
    "loso_f1  = loso_results.get('fine_f1_macro', 0)\n",
    "test_f1  = test_results.get('test_f1_macro', 0)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(5, 4))\n",
    "bars = ax.bar(['LOSO CV\\n(train)', 'Held-out\\n(test)'], [loso_f1, test_f1],\n",
    "              color=['#5DCAA5', '#7F77DD'], width=0.5)\n",
    "ax.set_ylim(0, 1.05)\n",
    "ax.set_ylabel('Macro F1')\n",
    "ax.set_title('Generalisation check: LOSO vs Test F1')\n",
    "for bar, val in zip(bars, [loso_f1, test_f1]):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,\n",
    "            f'{val:.3f}', ha='center', va='bottom', fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(RESULTS_DIR, 'fig_f1_comparison.png'), bbox_inches='tight')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb9cb3af",
   "metadata": {},
   "source": [
    "### 8.3  Feature importance (tier-colored)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5555f809",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Feature importance (tier-colored) ────────────────────────────────\n",
    "TIER_COLORS = {\n",
    "    'topology': '#8B5CF6',\n",
    "    'shape_pca': '#EC4899',\n",
    "}\n",
    "TIER_RANGES = {\n",
    "    'topology': (0, N_BASE_FEAT),\n",
    "    'shape_pca':(N_BASE_FEAT, 10**9),\n",
    "}\n",
    "def get_tier(name):\n",
    "    if name.startswith(SHAPE_PCA_NAME_PREFIX):\n",
    "        return 'shape_pca'\n",
    "    idx = feat_names.index(name) if name in feat_names else -1\n",
    "    for tier, (lo, hi) in TIER_RANGES.items():\n",
    "        if lo <= idx < hi:\n",
    "            return tier\n",
    "    return 'other'\n",
    "\n",
    "imp = MODEL_FINAL['clf'].feature_importances_\n",
    "feat_names = MODEL_FINAL['feature_names']\n",
    "order = np.argsort(imp)[::-1][:20]\n",
    "top20 = [(feat_names[i], imp[i]) for i in order]\n",
    "for name, val in top20:\n",
    "    print(f\"{name}: {val:.6f}\")\n",
    "colors = [TIER_COLORS.get(get_tier(feat_names[i]), '#aaa') for i in order]\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 5))\n",
    "ax.bar(range(len(order)), imp[order], color=colors)\n",
    "ax.set_xticks(range(len(order)))\n",
    "ax.set_xticklabels([feat_names[i] for i in order], rotation=45, ha='right', fontsize=8)\n",
    "ax.set_ylabel('Feature importance')\n",
    "ax.set_title('Top-20 features by GBM importance (color = tier)')\n",
    "from matplotlib.patches import Patch\n",
    "patches = [Patch(color=c, label=t) for t, c in TIER_COLORS.items()]\n",
    "ax.legend(handles=patches, loc='upper right', fontsize=8)\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(RESULTS_DIR, 'fig_feature_importance.png'), bbox_inches='tight')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3b66d312",
   "metadata": {},
   "source": [
    "---\n",
    "## 9. Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2ec31ac5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Pipeline summary ─────────────────────────────────────────────────\n",
    "print('='*80)\n",
    "print('PIPELINE SUMMARY')\n",
    "print('='*80)\n",
    "print(f'  Total sessions     : {len(ALL_SESSIONS)} entries '\n",
    "      f'({sum(1 for e in ALL_SESSIONS if e[4] is None)} homogeneous, '\n",
    "      f'{sum(1 for e in ALL_SESSIONS if e[4] is not None)} heterogeneous)')\n",
    "print(f'  Train entries      : {len(TRAIN_SESSIONS)}')\n",
    "print(f'  Test  entries      : {len(TEST_SESSIONS)}')\n",
    "print(f'  LOSO  macro-F1     : {loso_results.get(\"fine_f1_macro\",0):.3f}')\n",
    "print(f'  Test  macro-F1     : {test_results.get(\"test_f1_macro\",0):.3f}')\n",
    "n_train_cycles = MODEL_FINAL[\"X_train\"].shape[0]\n",
    "print(f'  Training cycles    : {n_train_cycles}')\n",
    "print(f'  Feature dim        : {MODEL_FINAL[\"X_train\"].shape[1]}')\n",
    "print(f'  Classes            : {list(MODEL_FINAL[\"label_encoder\"].classes_)}')\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}'''


def _strip_code_outputs(nb: dict) -> None:
    for cell in nb.get("cells", []):
        if cell.get("cell_type") == "code":
            cell["execution_count"] = None
            cell["outputs"] = []


def build_notebook(out_path: Path) -> None:
    nb = json.loads(NOTEBOOK_TEMPLATE_JSON)
    _strip_code_outputs(nb)
    out_path.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"Written: {out_path}  ({len(nb.get('cells', []))} cells)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build 08_Full_Pipeline_V08.ipynb from embedded template")
    parser.add_argument("--out", default=str(OUT_DEFAULT), help="Output .ipynb path")
    args = parser.parse_args()
    build_notebook(Path(args.out))


if __name__ == "__main__":
    main()
